# Brood disease reference — shared content for The Bee Bench (bench/build.py → brood-diseases.html)
# and the Bee Field Guide (bee-manual/build_data.py → "Brood Diseases" tile).
# Keep the two copies identical. Master copy: C:\Users\leasy\bee-sim\bench\brood_data.py — edit there, copy here.
#
# Written from standard apiculture diagnostics (USDA/extension brood-disease keys), in our own words.

# sev: high = serious/contagious, med = watch it, low = usually manageable, none = not a disease
# frame: slug of the matching drawing in the Frame Guide (bee-sim.allemanapiary.com/frames/<slug>)
BROOD = [
 {"name": "American Foulbrood (AFB)", "cause": "Bacteria — Paenibacillus larvae (spore-forming)", "sev": "high",
  "dies": "After capping — prepupa or pupa",
  "capped": "Yes. Cappings sunken, dark, greasy, often pierced",
  "color": "Dull white, then coffee, then dark brown",
  "texture": "Soft, sticky, glue-like",
  "rope": "Ropes 2 cm or more and snaps back",
  "scale": "Flat on the lower cell wall, black, will not come out",
  "smell": "Foul, like old glue (not always)",
  "look": "Spotty, shotgun brood pattern with sunken, pierced cappings scattered through it. Sometimes a dried pupal tongue sticks up from the scale toward the top of the cell.",
  "confused": "EFB (ropes less, dies before capping) and PMS (doesn't rope, mites present).",
  "do": "Close the hive, don't move frames or honey to other colonies, and reduce the entrance so nothing robs it. Confirm with a field kit or lab sample and call the state apiary inspector. Infected combs and frames are burned — the spores last for decades. Antibiotics only hide AFB, they never cure it, and in the US they need a veterinarian's order.",
  "frame": "american-foulbrood",
  "kw": "afb foul brood ropy ropey rope stringy scale sunken greasy pierced perforated cappings smell burn reportable paenibacillus pupal tongue"},

 {"name": "European Foulbrood (EFB)", "cause": "Bacteria — Melissococcus plutonius", "sev": "med",
  "dies": "Before capping — usually 4 to 5 day old larvae",
  "capped": "Mostly open cells; a few sunken cappings in bad cases",
  "color": "Dull white, then yellow, then brown; white breathing tubes may show",
  "texture": "Melted, twisted, slumped out of position",
  "rope": "Weak — 1.5 cm at most, often none",
  "scale": "Rubbery, twisted, easy to remove",
  "smell": "Sour, vinegary (not always)",
  "look": "Larvae twisted like a corkscrew or lying up the side of the cell instead of in a neat white C. Worst in spring, in colonies short on nurse bees or food.",
  "confused": "PMS looks almost the same — do a mite wash. Also AFB and sacbrood.",
  "do": "Often clears once the nectar flow picks up. Help it along: requeen (the brood break helps), feed, swap out old dark comb, or shake the bees onto new foundation if it's bad. Send a sample if you can't rule out AFB.",
  "frame": "european-foulbrood",
  "kw": "efb foul brood melted twisted corkscrew sour vinegar yellow uncapped open larvae melissococcus spring"},

 {"name": "Sacbrood", "cause": "Virus — sacbrood virus", "sev": "low",
  "dies": "After capping — stretched-out prepupa",
  "capped": "Yes. Cappings may have one or two holes",
  "color": "Pale yellow, then brown to black, head first",
  "texture": "A bag of watery, grainy fluid",
  "rope": "No",
  "scale": "Dry, brittle, boat-shaped, easy to remove",
  "smell": "None",
  "look": "Larva lying on its back with the dark head raised toward the cell opening — the canoe or Chinese-slipper shape. Lift it with tweezers and it comes out whole, like a little bag of water.",
  "confused": "AFB (sacbrood doesn't rope) and EFB.",
  "do": "No treatment. Usually shows up in spring and fades on its own. If it hangs on for several brood cycles, requeen.",
  "frame": "sacbrood",
  "kw": "sac bag fluid canoe slipper gondola boat virus watery head up"},

 {"name": "Chalkbrood", "cause": "Fungus — Ascosphaera apis", "sev": "low",
  "dies": "Around capping — mostly just-capped larvae",
  "capped": "Often uncapped by the bees; mummies in open cells",
  "color": "White, turning grey to black as the fungus fruits",
  "texture": "Hard, dry, chalk-like mummy",
  "rope": "No",
  "scale": "Loose mummy that rattles when you shake the frame",
  "smell": "None, maybe slightly musty",
  "look": "Mummies in the cells, on the bottom board, and dumped out front. Worst at the edges of the brood nest in cool, damp spring weather.",
  "confused": "Stonebrood (rock hard, yellow-green powder) and packed pollen (flat, colored, not larva-shaped).",
  "do": "A stress sign. Improve ventilation, tip the hive slightly forward so it drains, give it sun, keep the colony strong, and requeen with hygienic stock if it keeps coming back.",
  "frame": "chalkbrood",
  "kw": "chalk mummies mummy white grey black hard rattle fungus damp bottom board ascosphaera"},

 {"name": "Stonebrood", "cause": "Fungus — Aspergillus flavus / A. fumigatus", "sev": "med",
  "dies": "Before or after capping",
  "capped": "Either",
  "color": "Yellow-green powdery coat",
  "texture": "Rock hard, won't crush",
  "rope": "No",
  "scale": "Hard mummy, stuck or loose",
  "smell": "None",
  "look": "Mummies like chalkbrood but hard as stone and dusted with yellow-green spores. Rare. Can infect adult bees too.",
  "confused": "Chalkbrood.",
  "do": "Wear a dust mask — the same Aspergillus can make people sick if they breathe the spores. Remove and replace the affected comb and keep the colony strong and dry. Rare enough that a lab confirmation is worth having.",
  "frame": None,
  "kw": "stone aspergillus green yellow powder hard mummy fungus mask"},

 {"name": "Parasitic Mite Syndrome (PMS)", "cause": "Varroa mites and the viruses they carry", "sev": "high",
  "dies": "Many ages, open and capped",
  "capped": "Both; cappings chewed or pierced",
  "color": "Off-white to light brown",
  "texture": "Slumped and melted, like EFB",
  "rope": "No (a little at most)",
  "scale": "Rubbery, easy to remove",
  "smell": "None to faint",
  "look": "Spotty brood, slumped larvae, chewed-open cappings with pupae showing. Adults with crumpled wings. Mites on bees and in drone brood. Late summer and fall, when mite loads peak.",
  "confused": "EFB and AFB. A mite wash settles it.",
  "do": "Do a mite wash — it will be high. Treat now. A colony this far along may not recover, so combine it if it's weak.",
  "frame": "varroa-deformed-wing-virus",
  "kw": "pms varroa mites virus dwv deformed wings snotty spotty chewed cappings fall collapse"},

 {"name": "Chilled brood", "cause": "Not a disease — too few bees to keep the brood warm", "sev": "none",
  "dies": "Every age in one patch, all at once",
  "capped": "Both",
  "color": "Grey to black",
  "texture": "Soft, then dries",
  "rope": "No",
  "scale": "Easy to remove",
  "smell": "None to slight",
  "look": "A patch of dead brood of every age, usually at the edge of the brood nest, after a cold snap, a split, or a long inspection. Healthy brood right next to it.",
  "confused": "Foulbrood — but chilled brood kills every age at once and doesn't spread.",
  "do": "Nothing to treat. Don't make splits too small, keep cold-weather inspections short, and let the bees clean it out.",
  "frame": "chilled-brood",
  "kw": "chilled cold snap split edge patch all ages dead"},

 {"name": "Starved brood", "cause": "Not a disease — no food coming in", "sev": "none",
  "dies": "Open larvae first",
  "capped": "Mostly open",
  "color": "Dull white, drying",
  "texture": "Dried and shrunken",
  "rope": "No",
  "scale": "Dry, easy to remove",
  "smell": "None",
  "look": "Shriveled larvae in open cells, bees pulling them out and dumping them. No honey or pollen near the brood. Eggs may disappear. Often in a dearth or right after a split.",
  "confused": "EFB.",
  "do": "Feed syrup and pollen substitute now. Check the rest of the yard — a dearth hits every hive.",
  "frame": "starved-colony",
  "kw": "starved starving dearth hunger dried shriveled no food feed"},

 {"name": "Pesticide kill", "cause": "Not a disease — poisoning", "sev": "high",
  "dies": "Any age, suddenly",
  "capped": "Both",
  "color": "Varies",
  "texture": "Varies; larvae may crawl out of their cells",
  "rope": "No",
  "scale": "—",
  "smell": "None",
  "look": "Dead and twitching adults piled at the entrance along with dead brood, all at once. Can hit several hives in one yard on the same day.",
  "confused": "Any brood disease — the sudden pile of dead adults out front is the giveaway.",
  "do": "Photograph it, freeze a zip bag of the dead bees as a sample, and report it to the PA Department of Agriculture. Move or cover the hives if spraying nearby is still going on.",
  "frame": "pesticide-poisoning",
  "kw": "pesticide poison spray kill dead pile entrance twitching sudden"},

 {"name": "Bald brood", "cause": "Wax moth larvae tunnelling under the cappings", "sev": "low",
  "dies": "Usually survives",
  "capped": "Cappings removed in a line",
  "color": "Normal — purple-eyed pupae showing",
  "texture": "Healthy",
  "rope": "No",
  "scale": "None",
  "smell": "None",
  "look": "A straight or wandering row of uncapped cells with healthy pupae showing, following a moth tunnel. Silk threads under a magnifier.",
  "confused": "Chewed cappings from mites, or bees uncapping sick brood.",
  "do": "Usually minor. Keep the colony strong and it cleans it up.",
  "frame": "bald-brood",
  "kw": "bald brood wax moth tunnel uncapped row line pupae showing silk"},
]

# Columns for the side-by-side table: (key, header)
COLUMNS = [("dies", "Dies when"), ("capped", "Capped?"), ("color", "Color"), ("texture", "Feels like"),
           ("rope", "Rope test"), ("scale", "Scale"), ("smell", "Smell")]

# Start-here decision steps, in the order you'd check them at the frame.
STEPS = [
 "<b>Dead brood of every age in one patch, healthy brood beside it?</b> Chilled brood.",
 "<b>A pile of dead adults at the entrance too, all at once?</b> Pesticide kill.",
 "<b>Hard mummies?</b> Chalkbrood if white, grey or black. Stonebrood if rock hard with yellow-green powder.",
 "<b>Stick test ropes 2 cm or more and snaps back?</b> Treat it as AFB until proven otherwise. Close the hive and call the inspector.",
 "<b>Larva stretched out in a capped cell, full of fluid, dark head raised?</b> Sacbrood.",
 "<b>Twisted, melted larvae in open cells?</b> Do a mite wash first. High mites means PMS. Low mites means it's probably EFB.",
 "<b>Shriveled open larvae and no food in the hive?</b> Starved brood.",
 "<b>A row of uncapped cells with healthy pupae showing?</b> Bald brood from wax moth.",
]

TESTS = [
 ("Rope test", "Push a matchstick or twig into a suspect cell, stir, and pull it out slowly. AFB strings out 2 cm or more and snaps back like a rubber band. EFB may string a little and break. Nothing else ropes. Burn the stick afterward."),
 ("Field test kits", "Lateral flow kits for AFB and EFB (sold by beekeeping suppliers) give an answer in a few minutes from a single larva. Good for confirming a yes. A lab is still the final word."),
 ("Free lab test", "The USDA Bee Research Lab in Beltsville, MD tests brood samples for free. Cut a piece of comb about 2 by 2 inches with as many sick larvae as you can, no honey, wrap it in newspaper or a paper towel, and mail it in a small box. Never plastic, foil, or a zip bag — the sample rots and can't be tested. Check the lab's website for the current address and form."),
 ("State inspector", "Pennsylvania Department of Agriculture apiary inspectors will come look at no charge. With anything that might be foulbrood, call them. It protects every hive within flying distance of yours."),
]
