# Original beekeeping practice-test question bank (authored, not copied from the
# Cornell course quizzes). Facts are grounded in the course reference material.
# Each: q, opts (correct one FIRST here; the app shuffles), why, cat.
import json

Q = [
# ---------------- Biology & Anatomy ----------------
("How many main body segments does a honey bee have?",
 ["Three — head, thorax, abdomen","Two — head and body","Four","Six, one per leg pair"],
 "Like all insects, bees have three segments: head, thorax, and abdomen.","Biology"),
("Which honey bee develops from an UNfertilized egg?",
 ["The drone","The worker","The queen","The nurse bee"],
 "Drones are haploid — they hatch from unfertilized eggs and have only the mother's genes.","Biology"),
("Honey bees are haplodiploid. This means drones are…",
 ["Haploid (one set of chromosomes)","Diploid","Triploid","Sterile females"],
 "Drones are haploid; females (workers and queens) are diploid.","Biology"),
("What is 'bee space'?",
 ["About 3/8 inch","About 1/8 inch","About 1 inch","About 1/2 inch"],
 "3/8\" is the gap bees leave open. Smaller, they fill it with propolis; larger, they build burr comb.","Biology"),
("A queen mates with an average of about how many drones?",
 ["About 12","Exactly 1","About 3","About 50"],
 "Queens mate with ~12 drones (range 10–20) on 1–3 mating flights, boosting genetic diversity.","Biology"),
("Where are the glands that produce royal jelly located?",
 ["In the heads of nurse bees","In the abdomen","In the legs","In the sting"],
 "Hypopharyngeal glands in nurse bees' heads secrete royal jelly to feed larvae.","Biology"),
("Which organ stores sperm in the queen after mating?",
 ["The spermatheca","The crop","The Dufour's gland","An ovariole"],
 "The spermatheca stores sperm for the queen's whole life, releasing it to fertilize eggs.","Biology"),
("Worker bees secrete wax from glands located on the…",
 ["Underside of the abdomen","Head","Hind legs","Thorax"],
 "Wax glands sit on the underside of the worker's abdomen, most active before she becomes a forager.","Biology"),
("On average, honey bees spend how long as larvae?",
 ["About 6 days","About 1 day","About 12 days","About 21 days"],
 "All castes average ~6 days in the larval stage before pupating.","Biology"),
("Pollen is the colony's primary source of…",
 ["Protein","Carbohydrate","Water","Wax"],
 "Pollen (as bee bread) supplies protein, fats, vitamins and minerals; nectar supplies carbohydrate.","Biology"),
("Nectar is the colony's main source of…",
 ["Carbohydrate (energy)","Protein","Lipids","Minerals"],
 "Bees convert carbohydrate-rich nectar into honey for energy.","Biology"),
("A drone congregation area is where…",
 ["Drones gather in the air to mate with virgin queens","Bees cluster for winter","Foragers unload nectar","Robbing happens"],
 "Virgin queens fly to these areas to mate with many drones.","Biology"),
("Which female bee has a fully developed reproductive system?",
 ["The queen","A nurse bee","A forager","A guard bee"],
 "The queen is the only fully reproductive female; workers' ovaries are greatly reduced.","Biology"),
("Only which bees can sting?",
 ["Female bees","Male bees (drones)","Only the queen","All bees equally"],
 "The stinger is a modified ovipositor (egg-layer), so only females have one.","Biology"),

# ---------------- Behavior & Communication ----------------
("What does the waggle dance communicate?",
 ["Direction and distance to a resource","Time of day","The age of the queen","A swarm warning only"],
 "The waggle's angle gives direction and its duration gives distance to food or a nest site.","Behavior"),
("Below about what temperature do bees form a winter cluster?",
 ["64°F","45°F","75°F","32°F"],
 "Around 64°F bees cluster to stay warm; foraging and water collection stop.","Behavior"),
("Heater bees keep the brood nest at roughly…",
 ["91–97°F","75–80°F","100–105°F","60–65°F"],
 "Brood must be incubated at 91–97°F (33–36°C) to develop properly.","Behavior"),
("'Festooning' (bees hanging in chains by their legs) is associated with…",
 ["Wax construction","Defense","Robbing","Swarming"],
 "Festooning bees are usually building comb.","Behavior"),
("Robbing is when honey bees…",
 ["Steal honey/nectar from another colony","Collect water","Remove dead bees","Rob pollen from flowers"],
 "Robbing is bees taking stores from another colony instead of foraging flowers.","Behavior"),
("An orientation flight is taken to…",
 ["Learn the hive's location and surroundings","Mate","Find water","Defecate"],
 "Young bees take short orientation flights to memorize the hive location, also needed after a move.","Behavior"),
("A cleansing flight is when bees leave the hive to…",
 ["Defecate","Mate","Swarm","Collect propolis"],
 "Bees hold waste through winter and void it on warm days — fecal spots on snow can be a good sign.","Behavior"),
("The tremble dance recruits bees to…",
 ["Unload nectar from incoming foragers","Defend the hive","Build comb","Swarm"],
 "When a forager can't find a receiver bee, she tremble-dances to recruit more nectar handlers.","Behavior"),
("Bees can navigate using polarized light because they…",
 ["Can see it even through clouds","Have a magnetic sense","Follow scent trails only","Count landmarks"],
 "Bees detect polarized sunlight to orient while foraging, even on cloudy days.","Behavior"),
("Heavy orange/brown streaking on the front of a hive most likely signals…",
 ["Dysentery or disease","Healthy bees","A strong nectar flow","A new queen"],
 "A little fecal matter is normal; heavy streaking is a warning sign.","Behavior"),

# ---------------- Queens & Reproduction ----------------
("Many queen cells along the BOTTOM edge of frames usually indicate…",
 ["Swarm preparation","Supersedure","A healthy honey flow","Drone laying"],
 "Numerous cells low on the comb are swarm cells — the colony is preparing to split.","Queens"),
("A few queen cells near the CENTER of the comb usually indicate…",
 ["Supersedure or an emergency replacement","Swarming","Robbing","Normal drone rearing"],
 "Central cells usually mean the workers are replacing a failing or lost queen.","Queens"),
("Supersedure is…",
 ["Workers replacing an old or failing queen","A colony swarming","Two colonies merging","A queen killing drones"],
 "In supersedure the colony raises a new queen to replace the existing one, often without swarming.","Queens"),
("A laying worker's eggs develop into…",
 ["Drones","Workers","Queens","Nothing — they're infertile"],
 "Laying workers' eggs are unfertilized, so they become drones.","Queens"),
("Seeing multiple eggs in single cells most often means…",
 ["Laying workers are present","A very productive queen","Healthy brood","A disease"],
 "A good queen lays one egg per cell; multiple eggs per cell point to laying workers.","Queens"),
("Emergency queen cells are built when…",
 ["The colony suddenly loses its queen","The nectar flow ends","Drones are abundant","Winter approaches"],
 "Workers convert young worker larvae into queens after an abrupt queen loss.","Queens"),
("A 'queenright' colony is one that…",
 ["Has a laying queen","Has no queen","Has two queens","Is about to swarm"],
 "Queenright simply means a laying queen is present.","Queens"),
("In the Doolittle method of queen rearing, larvae are…",
 ["Grafted into artificial queen cups","Frozen and stored","Fed only honey","Left in worker cells"],
 "Young larvae are grafted into cups and given to cell-builder colonies to raise as queens.","Queens"),
("How many mating flights does a virgin queen typically take?",
 ["1 to 3","Exactly 1","About 10","She doesn't fly to mate"],
 "A queen takes 1–3 mating flights to a drone congregation area.","Queens"),
("Roughly what percentage of adult bees are drones at peak (late spring/early summer)?",
 ["About 5%","About 1%","About 25%","About 50%"],
 "~5% at peak. Far more capped drone late summer can signal a drone-laying queen.","Queens"),
("A nuc (nucleus colony) is…",
 ["A small colony of about 2–5 frames","A full double-deep hive","A queen cage","A swarm trap"],
 "Nucs are small colonies made by pulling frames and bees from larger ones.","Queens"),
("The 'mating sign' a returning queen may carry is…",
 ["Part of the drone's endophallus left behind","A scent marker","A torn wing","Pollen on her legs"],
 "When a drone mates, his endophallus ruptures; the tip may remain in the queen.","Queens"),

# ---------------- Pests & Diseases ----------------
("American foulbrood (AFB) is caused by a…",
 ["Bacterium","Fungus","Virus","Mite"],
 "AFB is caused by the spore-forming bacterium Paenibacillus larvae and is highly infectious.","Diseases"),
("The 'ropy test' (twisting a toothpick in a cell) checks for…",
 ["American foulbrood","Varroa","Nosema","Chalkbrood"],
 "If the larval remains rope out 2 cm+, suspect AFB.","Diseases"),
("Which disease leaves a hard, dark scale that will NOT scrape out of the cell?",
 ["American foulbrood","Chalkbrood","Sacbrood","Nosema"],
 "AFB scale sticks tightly to the cell wall — a key field clue.","Diseases"),
("Chalkbrood is caused by a…",
 ["Fungus","Bacterium","Virus","Mite"],
 "The fungus Ascosphaera apis turns larvae into hard chalky 'mummies.'","Diseases"),
("European foulbrood (EFB) is caused by a…",
 ["Bacterium","Fungus","Virus","Protozoan"],
 "EFB is caused by Melissococcus plutonius; larvae usually die before capping.","Diseases"),
("Nosema is a disease of the bee's…",
 ["Gut (a fungal parasite)","Wings","Trachea","Brood only"],
 "Nosema is a gut fungus; N. apis is linked with dysentery.","Diseases"),
("Deformed Wing Virus is spread mainly by…",
 ["Varroa mites","Wax moths","Small hive beetles","Robbing"],
 "Varroa vectors DWV — crumpled wings are a red flag for high mite loads.","Diseases"),
("Sacbrood is caused by a…",
 ["Virus","Bacterium","Fungus","Mite"],
 "Sacbrood virus leaves fluid-filled, sac-like larvae that turn brown.","Diseases"),
("Wax moths are mainly a problem in…",
 ["Weak colonies and stored comb","Strong colonies","Honey supers on strong hives","Queen cells"],
 "Wax moths exploit weak colonies and unprotected stored comb.","Diseases"),
("Which problem is the most serious and often requires burning equipment?",
 ["American foulbrood","Chalkbrood","Wax moth","Sacbrood"],
 "AFB spores survive decades; burning is often the only sure control.","Diseases"),
("Where can U.S. beekeepers send samples for FREE disease diagnosis?",
 ["The Beltsville Bee Lab (USDA)","A local pharmacy","The post office","No such service exists"],
 "The USDA Beltsville Bee Lab in Maryland offers free diagnosis.","Diseases"),
("Tracheal mites live and feed inside the bee's…",
 ["Tracheae (breathing tubes)","Stomach","Sting","Brain"],
 "Acarapis woodi infests the tracheae, feeding on hemolymph.","Diseases"),
("Small white 'guanine' crystals on the ceilings of brood cells indicate…",
 ["High Varroa mite levels","Healthy brood","American foulbrood","Good nutrition"],
 "Guanine deposits are mite waste — a sign of heavy Varroa.","Diseases"),
("Dysentery (brown streaking inside/outside the hive) is most associated with…",
 ["Nosema","Varroa","Wax moth","Chalkbrood"],
 "Nosema apis in particular is linked with dysentery.","Diseases"),
("Chalkbrood 'mummies' look like…",
 ["Hard, chalky white or black larvae","Brown ropy goo","Sac-like fluid larvae","Normal capped brood"],
 "Affected larvae dry into chalk-like mummies that may rattle in cells or appear at the entrance.","Diseases"),
("A small, fast black beetle that slimes the comb in warm, humid conditions is the…",
 ["Small hive beetle","Wax moth","Carpenter bee","Hive tool beetle"],
 "Small hive beetle larvae ferment and ruin comb and honey, worst in heat and humidity.","Diseases"),

# ---------------- Varroa ----------------
("Varroa mites reproduce…",
 ["Inside capped brood cells","On adult bees only","In honey cells","In pollen stores"],
 "A foundress mite enters a cell before capping and raises offspring on the developing pupa.","Varroa"),
("Varroa prefer to reproduce in which type of brood?",
 ["Drone brood","Queen cells","Worker brood only","They don't prefer any"],
 "Drone brood's longer development lets mites raise more mature daughters.","Varroa"),
("The 'phoretic' (dispersal) phase of Varroa is when mites are…",
 ["Riding on adult bees","Inside capped cells","In the honey","Dormant in wax"],
 "Phoretic mites travel on adult bees between brood cells and colonies.","Varroa"),
("A reliable way to monitor Varroa levels is…",
 ["An alcohol wash or sugar roll","Looking at the entrance","Counting drones","Weighing the hive"],
 "Washing a half-cup of bees gives an actual mite count; eyeballing bees does not.","Varroa"),
("Which Varroa treatment's active ingredient is amitraz?",
 ["Apivar","Apiguard","MiteAway Quick Strips","Oxalic acid"],
 "Apivar uses amitraz; supers must be off and you wait 2 weeks after.","Varroa"),
("Which treatment uses formic acid and can be used with honey supers on?",
 ["MiteAway Quick Strips","Apivar","Apiguard","Api Life Var"],
 "MAQS (formic acid) can stay on during a 7-day treatment, but needs moderate temps.","Varroa"),
("Oxalic acid works best when the colony is…",
 ["Broodless (e.g., late fall)","Full of capped brood","In peak honey flow","Swarming"],
 "Oxalic doesn't penetrate capped brood, so it's most effective when little/no brood is present.","Varroa"),
("Which two products are NOT recommended due to resistance and wax residues?",
 ["Apistan and CheckMite+","Apivar and Apiguard","Oxalic and formic acid","HopGuard and MAQS"],
 "Both persist in wax for years and mites have widespread resistance.","Varroa"),
("Thymol-based treatments like Apiguard need what conditions to work well?",
 ["Warm temperatures","Freezing temperatures","Total darkness","High humidity only"],
 "Thymol must vaporize, so it needs warmth (roughly 60–105°F).","Varroa"),
("Why should you rotate Varroa treatments?",
 ["To slow the development of resistance","To save money","Because the law requires it","To attract more bees"],
 "Rotating chemistries and following IPM reduces the chance mites become resistant.","Varroa"),

# ---------------- Management & Inspection ----------------
("At minimum, how many brood frames should you inspect per box?",
 ["At least 4","Just 1","All 10 every time","None — check the outside only"],
 "Inspecting at least 4 brood frames gives a fair picture without over-disturbing the nest.","Management"),
("A healthy brood frame looks like a…",
 ["Rainbow — brood center, pollen arc, honey on top","Solid sheet of honey","Random scatter","Wall of drone cells"],
 "Brood in the center, ringed by pollen, then honey, with only 6–17% empty cells.","Management"),
("Each year you should aim to replace how many of the oldest frames per box?",
 ["The 2 oldest","All of them","None","Half the box"],
 "Rotating out the 2 oldest frames yearly removes built-up pathogens and pesticides.","Management"),
("You should never remove more than how many frames from a hive at once?",
 ["4","8","2","There's no limit"],
 "Pulling more than 4 at once diverts the colony into comb-building instead of brood/honey.","Management"),
("A 1:1 sugar syrup (equal sugar and water) is mainly used to…",
 ["Stimulate brood rearing in spring","Build winter stores","Treat mites","Make honey"],
 "Thin 1:1 syrup mimics a nectar flow and stimulates the queen to lay.","Management"),
("A 2:1 sugar syrup (twice as much sugar) is mainly used to…",
 ["Build stores for winter in fall","Stimulate spring brood","Feed in mid-summer flow","Treat disease"],
 "Thick 2:1 syrup helps colonies pack away winter stores.","Management"),
("Scratch marks at the hive entrance most likely mean…",
 ["Skunks","Mice inside","A strong colony","Robbing bees"],
 "Skunks scratch to lure bees out and eat them; raising the hive on a stand helps.","Management"),
("When examining a brood frame, you should hold it with…",
 ["The sun at your back, light shining into the cells","The sun in your eyes","The frame flat and level","Your shadow over it"],
 "Backlighting the cells reveals eggs, larvae and the brood pattern.","Management"),
("Integrated Pest Management (IPM) means you treat when pests…",
 ["Reach or exceed a threshold","Are first seen at all","Are gone","Only in winter"],
 "IPM uses monitoring and treats based on thresholds, reducing unnecessary chemical use.","Management"),
("Putting frames back in the same order and orientation helps…",
 ["Keep the brood nest intact","Confuse robbers","Speed up honey flow","Mark the queen"],
 "The nest is organized; scrambling frames disrupts brood and stores.","Management"),

# ---------------- Nutrition & Forage ----------------
("Bee bread is…",
 ["Fermented, stored pollen","Capped honey","Royal jelly","A pollen substitute"],
 "Pollen packed with honey and microbes ferments into bee bread, a key protein source.","Nutrition"),
("A 'dearth' is a period when…",
 ["Little nectar or pollen is available","Bees swarm","Mites peak","Honey is harvested"],
 "During a dearth, forage is scarce and robbing risk rises.","Nutrition"),
("Abundant white royal jelly pooled around young larvae indicates…",
 ["Good colony nutrition","Starvation","Disease","Queenlessness"],
 "Plenty of jelly means nurses have enough protein; thin/no jelly suggests feeding is needed.","Nutrition"),
("A pollen SUBSTITUTE differs from a supplement because it…",
 ["Contains no real pollen","Is made only of honey","Includes natural pollen","Is fed only in winter"],
 "Substitutes (soy, yeast, milk powder) have no pollen; supplements mix in some real pollen.","Nutrition"),
("Ideal pollen/bee-bread stores for brood rearing are about…",
 ["1–2 frames per brood box","None needed","A full box","Only what fits in one cell"],
 "Roughly 1–2 frames of pollen per brood box supports healthy brood rearing.","Nutrition"),
("Seeing 10–20 bees per minute entering with full pollen baskets indicates…",
 ["A good resource flow","Robbing","A failing colony","Swarming"],
 "Steady incoming pollen is a sign lots of resources are coming into the colony.","Nutrition"),

# ---------------- Honey, Products & Business ----------------
("Bees cap honey when its moisture is about…",
 ["17–19%","30–35%","5–8%","Exactly 25%"],
 "At ~17–19% water the honey is ripe and the bees cap it.","Honey & Business"),
("Honey is at risk of fermenting when moisture rises above about…",
 ["18%","10%","5%","2%"],
 "Above ~18% moisture, wild yeasts can ferment honey.","Honey & Business"),
("Crystallization in honey is the formation of…",
 ["Glucose crystals","Wax flakes","Mold","Air bubbles"],
 "Glucose naturally crystallizes; it doesn't mean the honey is spoiled.","Honey & Business"),
("Propolis is made by bees from…",
 ["Tree resins (mixed with wax)","Pure beeswax","Pollen only","Nectar"],
 "Foragers gather plant resins and mix them with wax to seal and protect the nest.","Honey & Business"),
("A hive 'stocking rate' refers to…",
 ["Hives needed per area of a crop for pollination","Bees per frame","Honey per hive","Frames per box"],
 "Stocking rate is how many colonies an acre/crop needs for adequate pollination.","Honey & Business"),
("A pollination contract is an agreement between…",
 ["A grower and a beekeeper","Two beekeepers","A bee and a flower","A state and a farmer"],
 "It's a binding contract for renting colonies to pollinate a crop.","Honey & Business"),
("Mead is made by fermenting…",
 ["Honey with water","Pollen","Beeswax","Nectar straight from flowers"],
 "Mead is an alcoholic drink fermented from honey and water.","Honey & Business"),
("Ultrafiltered honey (every particle removed) is legally considered…",
 ["A sweetener, not honey","Premium honey","Organic honey","Raw honey"],
 "The FDA classes ultrafiltered product as a sweetener because pollen and all particles are gone.","Honey & Business"),
]

try:
    from quiz_more import MORE
    Q = Q + MORE
except Exception as e:
    print("(no quiz_more:", e, ")")

cats = []
for cat in [q[3] for q in Q]:
    if cat not in cats: cats.append(cat)

# guard against accidental duplicate question stems
seen = {}
for i, q in enumerate(Q):
    k = q[0].strip().lower()
    if k in seen: print("DUPLICATE question:", q[0])
    seen[k] = i

out = [{"q": q, "opts": opts, "a": 0, "why": why, "cat": cat} for (q, opts, why, cat) in Q]
json.dump(out, open(r"C:\Users\leasy\bee-manual\quiz.json","w",encoding="utf-8"),
          ensure_ascii=False, indent=1)
from collections import Counter
c = Counter(q[3] for q in Q)
print("Questions:", len(out))
for cat in cats: print(f"  {cat}: {c[cat]}")
