# Additional ORIGINAL questions (batch 3): Anatomy, Development, more Diseases & Varroa/IPM.
# Same (q, opts, why, cat) format; opts[0] is correct (the app shuffles).
MORE2 = [
# ---------------- Anatomy ----------------
("The jaws a bee uses to work wax, groom, and bite are called…",
 ["Mandibles","Ocelli","Tarsi","Spiracles"],
 "Mandibles are the bee's jaws, used for comb work, grooming and defense.","Anatomy"),
("A worker bee usually dies after stinging a mammal because her stinger is…",
 ["Barbed and tears out of her body","Made of wax","Too short","Coated in venom"],
 "Barbs anchor the worker's sting in skin; pulling away is fatal. A queen's sting is smooth.","Anatomy"),
("A queen can sting more than once because her stinger is…",
 ["Smooth (not barbed)","Longer","Hollow","Retractable into a pouch"],
 "The queen's smooth stinger doesn't lodge, so she can reuse it (mainly on rival queens).","Anatomy"),
("Each large compound eye is made of thousands of units called…",
 ["Facets (ommatidia)","Ocelli","Antennae","Hamuli"],
 "Compound eyes are built from many facets that together form an image.","Anatomy"),
("On each side, the front and hind wings are joined in flight by tiny hooks called…",
 ["Hamuli","Tarsi","Ocelli","Spiracles"],
 "Hamuli link the wing pair so they beat as one, looking like two wings instead of four.","Anatomy"),
("How many pairs of antennae does a honey bee have?",
 ["One pair","Two pairs","Three pairs","None"],
 "Bees have a single pair of segmented antennae, their main smell/touch organs.","Anatomy"),
("The honey bee stinger evolved from the female…",
 ["Ovipositor (egg-laying organ)","Proboscis","Antenna","Mandible"],
 "Because the sting is a modified ovipositor, only females can sting.","Anatomy"),
("Drones have especially large eyes mainly to…",
 ["Spot and chase queens during mating flights","See in the dark hive","Find flowers","Detect predators"],
 "A drone's big eyes help him find a fast-flying virgin queen in the air.","Anatomy"),
("Bee venom is stored in the…",
 ["Venom sac attached to the sting","Honey crop","Mandibular gland","Fat body"],
 "The venom sac feeds the sting; barbs let a torn-out sting keep pumping venom.","Anatomy"),
("Queen pheromone is produced mainly by the queen's…",
 ["Mandibular glands","Wax glands","Malpighian tubules","Spiracles"],
 "The mandibular glands are the main source of the queen's pheromone blend.","Anatomy"),
("Honey bees have an 'open' circulatory system, meaning hemolymph…",
 ["Flows freely through the body cavity","Is pumped through veins and arteries","Doesn't move at all","Is stored in the crop"],
 "There are no closed vessels; hemolymph bathes the organs directly.","Anatomy"),
("The wax-producing glands are most active in workers that are…",
 ["Young house bees (before they forage)","Old foragers","Drones","The queen"],
 "Wax glands on the abdomen peak before a worker graduates to foraging.","Anatomy"),
("A bee's tough outer shell (exoskeleton) is made largely of…",
 ["Chitin","Wax","Keratin","Calcium"],
 "Chitin forms the protective, jointed exoskeleton of all arthropods.","Anatomy"),
("The middle body segment, where the wings and legs attach, is the…",
 ["Thorax","Abdomen","Head","Proboscis"],
 "The thorax is the locomotion center, between the head and abdomen.","Anatomy"),
("Royal jelly is secreted by which glands of nurse bees?",
 ["Hypopharyngeal glands","Wax glands","Nasonov gland","Venom gland"],
 "Hypopharyngeal glands in the heads of nurse bees produce royal jelly.","Anatomy"),
("'Corbicula' is another name for the…",
 ["Pollen basket on the hind leg","Honey stomach","Compound eye","Wax mirror"],
 "The corbicula (pollen basket) on the hind leg carries pollen and resin home.","Anatomy"),

# ---------------- Development ----------------
("Eggs of all three castes hatch into larvae on about day…",
 ["3","1","7","12"],
 "An egg stands up, then tips over and hatches around day 3.","Development"),
("Which caste has the SHORTEST egg-to-adult development?",
 ["Queen (~16 days)","Worker (~21 days)","Drone (~24 days)","They're all equal"],
 "Queens develop fastest at about 16 days.","Development"),
("Which caste has the LONGEST egg-to-adult development?",
 ["Drone (~24 days)","Queen (~16 days)","Worker (~21 days)","Nurse bee"],
 "Drones take the longest, roughly 24 days.","Development"),
("A WORKER bee emerges about how many days after the egg is laid?",
 ["21 days","16 days","24 days","30 days"],
 "Worker: egg 3 days, larva ~6, then capped and pupating until ~day 21.","Development"),
("Worker brood cells are typically capped around day…",
 ["8–9","3","16","21"],
 "After ~6 days as a larva, worker cells are capped around day 8–9.","Development"),
("The developmental stage between larva and adult, inside a capped cell, is the…",
 ["Pupa","Egg","Prepupa only","Nymph"],
 "During the pupal stage the bee undergoes metamorphosis into an adult.","Development"),
("A virgin queen generally takes her mating flights within about…",
 ["The first 1–2 weeks after emerging","The first day","Two months","A full year"],
 "Queens usually mate roughly 5–14 days after emerging, weather permitting.","Development"),
("A queen typically starts laying eggs about how long after mating?",
 ["2–3 days","Same day","2 weeks","2 months"],
 "After her mating flights she begins laying within a couple of days.","Development"),
("A drone becomes sexually mature about how many days after emerging?",
 ["About 12 days","The same day","About 2 hours","About 40 days"],
 "Drones need roughly 10–14 days to mature before they can mate.","Development"),
("Capped DRONE brood looks different from worker brood because it is…",
 ["Raised and bullet-shaped","Flat and sunken","Bright white","Hexagonal and open"],
 "Drone cappings dome up like bullets; worker cappings are flatter and tan.","Development"),
("The 'step-down' aging of larvae (rings of different-age brood) results from…",
 ["The queen laying outward in concentric circles","Random egg-laying","Workers moving eggs","Disease"],
 "A good queen lays from the center outward, so brood ages in neat rings.","Development"),
("Which sequence is the honey bee's complete life cycle?",
 ["Egg → larva → pupa → adult","Egg → pupa → larva → adult","Larva → egg → pupa → adult","Egg → nymph → adult"],
 "Bees undergo complete metamorphosis with a distinct pupal stage.","Development"),
("A newly emerged worker's very first job in the hive is usually…",
 ["Cleaning cells","Foraging for nectar","Guarding the entrance","Mating"],
 "Workers move through age-based tasks (polyethism), starting with cell cleaning.","Development"),
("Developing queens differ from workers mainly because they are fed…",
 ["Royal jelly throughout the larval stage","Only honey","Only pollen","Less food overall"],
 "A flood of royal jelly the whole larval period makes a larva become a queen.","Development"),

# ---------------- Diseases (more depth) ----------------
("Parasitic Mite Syndrome (PMS) is colony decline driven by…",
 ["Varroa mites together with the viruses they spread","Pesticides only","Poor nutrition only","Wax moths"],
 "PMS combines mite feeding damage with virus loads, causing spotty brood and decline.","Diseases"),
("'Chilled brood' usually happens when…",
 ["Too few adult bees cover the brood in cold weather","The hive is too warm","Mites are absent","There is too much honey"],
 "Brood left uncovered (small cluster, or over-inspection on a cold day) can die of cold.","Diseases"),
("Brown spotting on snow from winter 'cleansing flights' is…",
 ["Normal — even a good sign the bees got out to defecate","Always a sign of disease","Caused by Varroa","A pesticide symptom"],
 "A bit of fecal matter after winter confinement is healthy; heavy streaking is the worry.","Diseases"),
("A 'spotty' or shotgun brood pattern can be caused by…",
 ["Disease, a poor/inbred queen, or hygienic removal","Only American foulbrood","Only good nutrition","Only cold weather"],
 "Many things cause a patchy pattern, so it's a clue to investigate, not a diagnosis.","Diseases"),
("Which is a REPORTABLE disease that many states legally regulate?",
 ["American foulbrood","Chalkbrood","Sacbrood","Wax moth damage"],
 "AFB is so contagious and persistent that reporting/control is often required by law.","Diseases"),
("EFB, sacbrood and chalkbrood often improve when the colony is…",
 ["Strong, well-fed, and/or requeened","Closed up tight","Stripped of honey","Moved at night"],
 "Good nutrition and a brood break from requeening help these clear up.","Diseases"),
("'Bald brood' — a line of uncapped pupae — is often a sign of…",
 ["Wax moth larvae tunneling under cappings","A new queen","A nectar flow","Good ventilation"],
 "Wax moth galleries (or hygienic uncapping) can leave a trail of exposed brood.","Diseases"),
("Idiopathic brood disease refers to sick brood with…",
 ["No identifiable known cause","A clear AFB cause","A clear Varroa cause","A clear pesticide cause"],
 "It looks like other brood diseases but no specific pathogen is found.","Diseases"),
("Many paralysis viruses and Deformed Wing Virus are amplified in a colony mainly by…",
 ["Varroa mites","Wax moths","Robbing screens","Pollen substitutes"],
 "Varroa both spreads and boosts these viruses, so mite control limits them.","Diseases"),

# ---------------- Varroa & IPM (more depth) ----------------
("IPM stands for…",
 ["Integrated Pest Management","Internal Pesticide Method","Insect Protection Mandate","Initial Pollination Measure"],
 "IPM blends monitoring, cultural, mechanical and (last) chemical controls.","Varroa"),
("Which is considered a 'soft' (natural) Varroa miticide?",
 ["Oxalic acid","Amitraz (Apivar)","Fluvalinate (Apistan)","Coumaphos (CheckMite+)"],
 "Oxalic, formic and thymol are 'soft' organic options; the others are synthetics.","Varroa"),
("A purely CULTURAL (non-chemical) Varroa control is…",
 ["Drone-brood trapping","Spraying Apivar","Vaporizing oxalic acid","Dribbling formic acid"],
 "Removing capped drone comb pulls out the mites that gathered in it — no chemicals.","Varroa"),
("Requeening to force a 'brood break' lowers mites because it…",
 ["Temporarily stops the capped brood mites need to reproduce","Poisons the mites","Repels mites with scent","Feeds the colony"],
 "No capped brood means mites can't reproduce, so their numbers fall.","Varroa"),
("For an accurate mite wash, you sample about how many bees?",
 ["About 300 (½ cup)","About 10","About 50","The whole frame"],
 "Roughly 300 nurse bees (½ cup) gives a reliable mites-per-100 reading.","Varroa"),
("The best bees to sample for mites come from…",
 ["A frame of nurse bees near the brood nest","The honey supers","The hive entrance","Drone congregation areas"],
 "Nurse bees near brood carry the most representative mite load.","Varroa"),
("Formic acid is unusual among Varroa treatments because it…",
 ["Can penetrate cappings to kill mites in the brood","Is harmless at any temperature","Stays in wax for years","Repels rather than kills"],
 "Formic acid reaches mites under the cappings, unlike most treatments.","Varroa"),
("A screened bottom board assists Varroa management by…",
 ["Letting groomed/fallen mites drop out of the hive","Trapping the queen","Warming the brood","Increasing honey"],
 "Mites that fall through can't climb back, and you can count the drop.","Varroa"),
("Untreated Varroa most often kills a colony by…",
 ["Producing weak, virus-laden winter bees that fail over winter","Eating all the honey","Scaring off the queen","Blocking the entrance"],
 "High mites in late summer cripple the winter bees, and the colony dies in winter.","Varroa"),
("Powdered-sugar dusting reduces mites by…",
 ["Prompting bees to groom mites off (limited effect)","Poisoning the mites","Suffocating brood","Killing the queen"],
 "Sugar makes bees groom off phoretic mites; it's a monitoring aid more than a cure.","Varroa"),
("'Mite-resistant' stocks like VSH or Russian bees keep mites down through…",
 ["Behavioral/genetic traits such as removing infested brood","Producing more honey","Larger body size","Stinging the mites"],
 "Selected traits interrupt mite reproduction without chemicals.","Varroa"),
("In an IPM program, chemical miticides should be used…",
 ["As a last resort, based on monitoring and thresholds","First, before checking mite levels","Every week regardless","Never, under any circumstance"],
 "IPM treats with chemicals only when monitoring shows mites exceed a threshold.","Varroa"),
]
