# Additional ORIGINAL practice questions (batch 2). Same (q, opts, why, cat) format;
# opts[0] is the correct answer (the app shuffles). Merged in by build_quiz.py.
MORE = [
# ---------------- Anatomy & Biology ----------------
("How many eyes does a honey bee have?",
 ["Five — two compound and three simple (ocelli)","Two","Three","Eight"],
 "Two large compound eyes plus three small ocelli that sense light intensity.","Biology"),
("The three small simple eyes on top of a bee's head are called…",
 ["Ocelli","Compound eyes","Spiracles","Antennae"],
 "Ocelli detect light intensity but can't form an image.","Biology"),
("How many wings does a honey bee have?",
 ["Four","Two","Six","Eight"],
 "Two pairs; hooks called hamuli link the front and hind wing on each side in flight.","Biology"),
("A bee's main organs of smell are its…",
 ["Antennae","Compound eyes","Mandibles","Wings"],
 "The antennae carry most of the bee's smell and touch receptors.","Biology"),
("Bees breathe through small openings along the body called…",
 ["Spiracles","Ocelli","Hamuli","Ovarioles"],
 "Air enters through spiracles and travels via tracheae to the tissues.","Biology"),
("The honey bee equivalent of blood is called…",
 ["Hemolymph","Plasma","Royal jelly","Lymph nodes"],
 "Hemolymph bathes the organs directly rather than flowing through veins.","Biology"),
("Bees draw up nectar and water using their…",
 ["Proboscis (tongue)","Mandibles","Antennae","Ovipositor"],
 "The proboscis is a tube the bee forms to suck up liquids.","Biology"),
("The honey bee organs that act like kidneys are the…",
 ["Malpighian tubules","Spiracles","Mandibular glands","Ocelli"],
 "Malpighian tubules filter waste from the hemolymph into the hindgut.","Biology"),
("Which bee has no stinger at all?",
 ["The drone","The worker","The queen","The nurse bee"],
 "Drones are male; the stinger is a modified egg-layer found only in females.","Biology"),
("A summer worker bee typically lives about…",
 ["6 weeks","6 days","6 months","2 years"],
 "Summer workers wear out in roughly 6 weeks; winter bees live for months.","Biology"),
("Winter bees survive for months partly because they have…",
 ["Larger fat bodies and more vitellogenin","Bigger wings","No stinger","Larger eyes"],
 "Winter bees are physiologically distinct, with large fat bodies for longevity.","Biology"),
("Vitellogenin in bees is important for…",
 ["Egg production, immunity and longevity","Flight muscle only","Wax color","Stinger strength"],
 "Vitellogenin supports egg-making, royal jelly, immune function and long life.","Biology"),
("The fat body of a bee mainly functions to…",
 ["Store energy and produce vitellogenin","Pump hemolymph","Digest pollen in the gut","Form the stinger"],
 "The fat body stores fat/glycogen and makes key proteins.","Biology"),
("The valve that keeps nectar in the honey crop from being digested is the…",
 ["Proventriculus","Spiracle","Hamulus","Ocellus"],
 "The proventriculus closes off the crop from the ventriculus (stomach).","Biology"),
("How many legs does a honey bee have?",
 ["Six","Four","Eight","Three"],
 "All insects have three pairs of legs.","Biology"),
("Pollen is carried back to the hive packed into the…",
 ["Pollen baskets (corbiculae) on the hind legs","Honey crop","Mandibles","Antennae"],
 "Foragers pack pollen pellets into the corbiculae on their hind legs.","Biology"),

# ---------------- Development ----------------
("From egg to adult, a QUEEN develops in about…",
 ["16 days","21 days","24 days","12 days"],
 "Queens are fastest at ~16 days; workers ~21; drones ~24.","Biology"),
("From egg to adult, a WORKER develops in about…",
 ["21 days","16 days","24 days","28 days"],
 "Workers take about 21 days from egg to emergence.","Biology"),
("From egg to adult, a DRONE develops in about…",
 ["24 days","21 days","16 days","30 days"],
 "Drones take the longest, about 24 days.","Biology"),
("A honey bee egg hatches into a larva after about…",
 ["3 days","1 day","7 days","12 days"],
 "Eggs of all castes hatch around day 3.","Biology"),
("Developing queens are fed royal jelly…",
 ["Their entire larval stage","Only the first day","Never","Only after capping"],
 "Queens get royal jelly throughout; workers only the first 2–3 days, then bee bread and honey.","Biology"),
("The order of honey bee metamorphosis is…",
 ["Egg → larva → pupa → adult","Egg → pupa → larva → adult","Larva → egg → pupa → adult","Egg → nymph → adult"],
 "Bees undergo complete metamorphosis through a distinct pupal stage.","Biology"),
("A peanut-shaped cell hanging downward off the comb is a…",
 ["Queen cell","Drone cell","Worker cell","Honey cell"],
 "Queen cells are large, vertical and peanut-textured.","Biology"),

# ---------------- Pheromones ----------------
("Workers sense their queen is present and healthy mainly through her…",
 ["Pheromones (queen substance)","Buzzing sound","Size","Color"],
 "Queen pheromone spreads through the colony; its decline signals queenlessness.","Behavior"),
("The alarm pheromone, which smells like bananas, is released when a bee…",
 ["Stings","Forages","Builds comb","Cleans cells"],
 "Alarm pheromone near the sting recruits other bees to defend.","Behavior"),
("Bees stand at the entrance and fan to release Nasonov pheromone in order to…",
 ["Help orient and recruit nestmates (mark home/water)","Cool the brood only","Signal danger","Attract drones"],
 "Nasonov pheromone marks the hive entrance, water, and swarm clusters.","Behavior"),
("Brood pheromone, released by larvae, helps…",
 ["Regulate nursing and worker development","Mark the hive entrance","Trigger stinging","Ripen honey"],
 "Larval brood pheromone influences foraging and suppresses worker ovaries.","Behavior"),

# ---------------- Behavior (more) ----------------
("Bees clustering OUTSIDE the entrance on a hot evening ('bearding') are usually…",
 ["Cooling off and ventilating the hive","Preparing to swarm","Being robbed","Sick"],
 "Bearding is normal heat behavior, not necessarily swarming.","Behavior"),
("Fanning at the entrance with the abdomen down often means bees are…",
 ["Cooling the hive or curing honey","Releasing alarm pheromone","Robbing","Orienting"],
 "Wing-fanning moves air to lower temperature and evaporate nectar moisture.","Behavior"),
("'Absconding' is when…",
 ["The entire colony abandons the hive","A queen is replaced","Bees rob another hive","Drones are evicted"],
 "Absconding is the whole colony leaving, often due to pests, disease or disturbance.","Behavior"),
("Undertaker bees are workers that…",
 ["Remove dead bodies and debris from the hive","Guard the entrance","Feed the queen","Build queen cells"],
 "A subset of middle-aged bees keeps the nest clean by removing corpses.","Behavior"),
("Drifting is when bees…",
 ["Enter the wrong hive by mistake","Leave to defecate","Form a swarm","Rob honey"],
 "Drift is common when hives look alike and sit close together.","Behavior"),
("In late fall, colonies evict their drones because…",
 ["Drones don't work and would drain winter stores","Drones carry disease","The queen stops laying","Drones sting"],
 "Drones are costly to feed and useless in winter, so workers force them out.","Behavior"),

# ---------------- Queens & Reproduction (more) ----------------
("A virgin queen flies to a drone congregation area to mate because it…",
 ["Promotes outbreeding with unrelated drones","Is closest to the hive","Has the most flowers","Is where workers gather"],
 "Mating away from home with many drones boosts genetic diversity and avoids inbreeding.","Queens"),
("Polyandry (a queen mating with many drones) benefits the colony by…",
 ["Increasing genetic diversity and disease resistance","Reducing the number of workers","Making bigger queens","Producing only drones"],
 "Diverse genetics helps the colony resist disease and adapt.","Queens"),
("Instrumental (artificial) insemination of queens is used to…",
 ["Control exactly which drones a queen mates with","Speed up egg laying","Feed the queen","Mark the queen"],
 "It gives breeders full control over genetics, unlike open mating.","Queens"),
("A two-queen colony is sometimes run to…",
 ["Boost honey production","Prevent swarming forever","Raise drones only","Make the bees gentler"],
 "Two laying queens build a huge population for bigger honey crops, kept apart by management.","Queens"),
("If you find eggs but cannot find the queen, a good rule is…",
 ["Eggs mean she was there in the last ~3 days — the colony is likely queenright","The colony is definitely queenless","Add a new queen immediately","Combine the colony"],
 "Fresh eggs are strong evidence of a recent laying queen even if you can't spot her.","Queens"),

# ---------------- Genetics & Stock ----------------
("The scientific name of the Italian honey bee subspecies is…",
 ["Apis mellifera ligustica","Apis mellifera carnica","Apis cerana","Apis dorsata"],
 "Italians are A. m. ligustica — prolific, light-colored, popular in the US.","Genetics"),
("Carniolan bees (Apis mellifera carnica) are especially known for…",
 ["Gentleness and rapid spring buildup","Aggression","Poor wintering","Tiny colonies"],
 "Carniolans are docile, overwinter well and build up fast in spring.","Genetics"),
("VSH (Varroa Sensitive Hygiene) is a trait where bees…",
 ["Detect and remove Varroa-infested pupae","Groom each other constantly","Make extra propolis","Swarm less"],
 "VSH bees interrupt mite reproduction by uncapping and removing infested brood.","Genetics"),
("Africanized honey bees are best described as…",
 ["A defensive hybrid of African and European bees","A separate species","Stingless bees","Sterile workers"],
 "They defend aggressively and abscond readily, but are the same species, A. mellifera.","Genetics"),
("'Hygienic behavior' in bees refers to workers…",
 ["Detecting and removing diseased or parasitized brood","Cleaning the entrance","Grooming the queen","Fanning honey"],
 "Hygienic colonies uncap and remove sick brood, reducing disease spread.","Genetics"),
("Open mating means a queen's offspring genetics are…",
 ["Uncertain — she mates with whatever drones are around","Fully controlled","Always Italian","Identical to her"],
 "With open mating you can't guarantee the drones' stock.","Genetics"),
("A 'stock' of bees is…",
 ["A group bred for a particular set of traits","A box of equipment","A swarm","A disease"],
 "Stock describes bees selected for traits like gentleness, honey, or mite resistance.","Genetics"),

# ---------------- Equipment ----------------
("The standard movable-frame hive used across North America is the…",
 ["Langstroth hive","Skep","Warré hive only","Log gum"],
 "The Langstroth design exploits bee space so frames lift out without damage.","Equipment"),
("A queen excluder is used to…",
 ["Keep the queen out of the honey supers","Trap drones","Block robbers","Catch swarms"],
 "Its gaps let workers through but stop the larger queen from laying in honey supers.","Equipment"),
("Smoke calms bees mainly by…",
 ["Masking alarm pheromone and prompting them to gorge on honey","Putting them to sleep","Poisoning mites","Cooling the hive"],
 "Smoke disrupts alarm communication and makes bees eat honey, which calms them.","Equipment"),
("Honey is removed from frames WITHOUT destroying the comb using a(n)…",
 ["Extractor","Smoker","Queen excluder","Uncapping the brood"],
 "An extractor spins honey out by centrifugal force so comb can be reused.","Equipment"),
("Before extracting, beekeepers remove the wax cappings by…",
 ["Uncapping with a knife, fork or roller","Freezing the frames","Smoking them","Washing with water"],
 "Cappings must come off so honey can spin out of the cells.","Equipment"),
("A screened bottom board helps with…",
 ["Ventilation and monitoring Varroa mite drop","Keeping the queen in","Honey extraction","Feeding syrup"],
 "Mites that fall through the screen can be counted, and airflow improves.","Equipment"),
("An entrance reducer is mainly used to…",
 ["Help a colony defend against robbing and cold","Increase honey flow","Mark the queen","Catch pollen"],
 "Shrinking the entrance helps weak or wintering colonies guard and stay warm.","Equipment"),
("Medium ('honey super') boxes are often preferred over deeps for honey because…",
 ["They're lighter to lift when full","They hold more honey","Bees prefer them","They resist mites"],
 "A full deep of honey is very heavy; mediums are easier on the back.","Equipment"),
("Comb foundation in a frame serves to…",
 ["Guide bees to build straight, worker-sized comb","Feed the bees","Kill mites","Insulate the hive"],
 "Foundation gives bees a template for even comb on the frame.","Equipment"),
("A nuc (nucleus) box is typically used to…",
 ["House a small starter colony of a few frames","Store honey","Catch falling mites","Transport the extractor"],
 "Nucs hold 2–5 frames to start or bank a small colony.","Equipment"),

# ---------------- Pests (more) ----------------
("To keep mice out of a hive over winter, beekeepers commonly use…",
 ["An entrance reducer or mouse guard","A queen excluder","A pollen trap","An extractor"],
 "Mice nest in winter clusters; a small entrance or metal guard blocks them.","Diseases"),
("The most effective protection against bears at an apiary is…",
 ["A properly built electric fence","An entrance reducer","Painting the hives","Adding more supers"],
 "Bears destroy hives for brood and honey; strong electric fencing is the standard defense.","Diseases"),
("A robbing screen works by…",
 ["Forcing resident bees to learn a detour while confusing robbers","Killing robber bees","Trapping the queen","Catching pollen"],
 "It reroutes the entrance so robbers can't find a straight way in.","Diseases"),
("Yellowjackets are most likely to attack honey bee colonies in…",
 ["Late summer and fall","Early spring","Mid-winter","During the main nectar flow"],
 "Yellowjacket pressure peaks August–October as their own food runs short.","Diseases"),
("A 'zombee' is a honey bee parasitized by a…",
 ["Phorid fly","Varroa mite","Wax moth","Tracheal mite"],
 "Phorid fly larvae cause erratic night-flying behavior, hence 'zombee.'","Diseases"),
("'Mite bombs' refer to…",
 ["Collapsing colonies whose mites spread to others via robbing","A treatment device","A type of swarm","A pesticide"],
 "When a heavily-infested colony crashes, robbing bees carry its mites home.","Varroa"),

# ---------------- Varroa (more) ----------------
("A commonly cited Varroa action threshold is about…",
 ["3 mites per 100 bees","30 mites per 100 bees","1 mite per 1,000 bees","No threshold — never treat"],
 "Many guides suggest treating when mite loads pass ~3 per 100 bees, lower before winter.","Varroa"),
("Compared with an alcohol wash, a powdered-sugar (sugar) roll is…",
 ["Non-lethal but can be less accurate","More lethal","Useless","Only for tracheal mites"],
 "The sugar roll spares the sampled bees; alcohol washes tend to give higher, more reliable counts.","Varroa"),
("Drone-brood trapping controls Varroa by…",
 ["Luring mites into drone comb that you then remove","Poisoning the mites","Repelling mites with scent","Starving the colony"],
 "Mites prefer drone brood; removing capped drone frames removes the mites in them.","Varroa"),
("It's especially important to knock down Varroa in late summer to…",
 ["Protect the winter bees being raised then","Increase the honey crop","Encourage swarming","Boost drone numbers"],
 "Mites peak as the colony shrinks; healthy winter bees are essential for survival.","Varroa"),
("Oxalic acid 'vaporization' works by…",
 ["Heating the acid so it sublimates and coats the bees","Dissolving it in syrup","Spraying brood directly","Burning the mites"],
 "A vaporizer sublimates oxalic crystals into a vapor that settles on the bees.","Varroa"),
("Why should you remove Varroa treatment strips on schedule rather than leaving them in?",
 ["Leaving them in promotes mite resistance","They attract robbers","They feed the queen","They cause swarming"],
 "Lingering low-dose exposure helps mites develop resistance.","Varroa"),

# ---------------- Pesticides & Toxicology ----------------
("The LD50 of a pesticide is the dose that…",
 ["Kills half of a test population","Kills every bee","Kills no bees","Repels bees"],
 "LD50 is the median lethal dose — a standard measure of acute toxicity.","Pesticides"),
("Neonicotinoid insecticides harm bees by…",
 ["Overstimulating their nervous system","Blocking digestion","Dissolving the exoskeleton","Causing dehydration only"],
 "Neonics bind acetylcholine receptors, causing neurons to fire uncontrollably.","Pesticides"),
("A 'systemic' pesticide is one that…",
 ["Spreads throughout all parts of the treated plant","Stays only on the leaf surface","Evaporates instantly","Only affects soil"],
 "Systemics like neonics move into nectar and pollen, exposing bees.","Pesticides"),
("'Sublethal' pesticide effects on bees include…",
 ["Impaired navigation, learning or reproduction","Instant death","No effect at all","Only killing mites"],
 "Sublethal doses don't kill outright but harm behavior and colony health.","Pesticides"),
("To reduce bee kills, pesticides should ideally be applied…",
 ["In the evening when bees aren't foraging","At midday on a sunny bloom","During the nectar flow peak","Only when bees are active"],
 "Spraying when foragers are home and blooms are closed reduces exposure.","Pesticides"),
("An insecticide is a pesticide that targets…",
 ["Insect pests","Weeds","Fungi","Rodents"],
 "Herbicides target plants, fungicides target fungi, insecticides target insects.","Pesticides"),
("'Entombed pollen' (cells of pollen sealed over with propolis and wax) often contains…",
 ["High levels of pesticides","Extra protein","Royal jelly","Mite eggs"],
 "Bees wall off contaminated pollen; it's been linked to high pesticide residues.","Pesticides"),

# ---------------- Nutrition (more) ----------------
("Bees collect water primarily to…",
 ["Cool the hive and dilute stored food","Make wax","Build comb","Produce venom"],
 "Water is used for evaporative cooling and to thin honey for feeding brood.","Nutrition"),
("Pollen provides bees with protein, fats, minerals and…",
 ["Vitamins","Pure sugar","Wax","Water only"],
 "Pollen is the colony's complete protein/micronutrient source; nectar gives carbs.","Nutrition"),
("Bees need the MOST protein when they are…",
 ["Rearing lots of brood","Clustered in winter","Foraging for water","Making wax only"],
 "Brood rearing demands protein for nurse bees to make royal jelly.","Nutrition"),
("Turning nectar into honey involves removing water and adding…",
 ["Enzymes like invertase","Pollen grains","Wax","Propolis"],
 "Enzymes break sucrose into simpler sugars while bees evaporate moisture.","Nutrition"),
("A diverse mix of pollen colors in the hive generally indicates…",
 ["Better overall nutrition","A disease","Robbing","Queenlessness"],
 "Varied pollen sources provide a fuller amino-acid profile.","Nutrition"),
("In fall, beekeepers feed colonies to…",
 ["Help them reach enough stored weight for winter","Stop them from making honey","Trigger swarming","Kill mites"],
 "Fall feeding (often 2:1 syrup) tops up winter stores.","Nutrition"),

# ---------------- Honey, Products & Business (more) ----------------
("Honey should never be fed to children under 1 year old because of the risk of…",
 ["Infant botulism","Tooth decay","Allergies","Choking"],
 "Honey can carry Clostridium botulinum spores dangerous to infants.","Honey & Business"),
("Honey resists spoiling mainly because of its…",
 ["Low moisture, low pH and hydrogen peroxide","High protein","Wax content","Pollen"],
 "Few microbes survive honey's dryness, acidity and natural peroxide.","Honey & Business"),
("Monofloral honey (like clover or orange blossom) comes from…",
 ["Mostly one type of flower","A blend of many flowers","Sugar syrup","Honeydew only"],
 "Monofloral honeys are dominated by nectar from a single plant.","Honey & Business"),
("Producing beeswax is 'expensive' for bees because they must…",
 ["Eat a lot of honey to secrete wax","Stop foraging entirely","Lose their stingers","Abandon the brood"],
 "Bees consume roughly several pounds of honey per pound of wax made.","Honey & Business"),
("Propolis benefits the colony largely through its…",
 ["Antimicrobial properties","Sweetness","Wax content","Water storage"],
 "Resin-based propolis seals the nest and helps fight pathogens.","Honey & Business"),
("The largest managed pollination event in the United States is for…",
 ["Almonds in California","Apples in New York","Blueberries in Maine","Pumpkins"],
 "Each spring well over a million colonies are trucked in to pollinate California almonds.","Honey & Business"),
("Honey bees are estimated to help pollinate roughly what share of the food crops we eat?",
 ["About one third","About one tenth","Nearly all","Almost none"],
 "Pollinators are tied to about a third of crop foods, a common teaching figure.","Honey & Business"),

# ---------------- Management & Seasonal ----------------
("Two colonies are most commonly united using the…",
 ["Newspaper method","Queen excluder method","Sugar-roll method","Smoke method"],
 "A sheet of newspaper between boxes lets the two slowly merge scents without fighting.","Management"),
("Queens are often marked with a paint color that indicates…",
 ["The year she was born","Her subspecies","Her temperament","The apiary number"],
 "An international color code (white, yellow, red, green, blue) tracks the queen's age.","Management"),
("When moving a hive a short distance, the rule of thumb is to move it…",
 ["Less than 3 feet, or more than a couple miles","Exactly 100 feet","Any distance, anytime","Only at noon"],
 "Foragers reorient if moved far; small in-place nudges avoid losing them.","Management"),
("During swarm season, strong colonies are best inspected about every…",
 ["7–10 days","2 months","Day","Hour"],
 "Weekly checks catch swarm cells before the colony issues a swarm.","Management"),
("'Hefting' a hive means…",
 ["Lifting the back to judge how heavy (how much stores)","Painting it","Moving it","Splitting it"],
 "A quick lift estimates food reserves, especially heading into winter.","Management"),
("A common way to PREVENT swarming is to…",
 ["Give the colony more room or make a split","Close the entrance","Remove all the honey","Stop inspecting"],
 "Relieving congestion — adding space, supering, or splitting — reduces the swarm urge.","Management"),
("In the Northeast, a colony generally needs roughly how much stored honey to survive winter?",
 ["About 60–90 pounds","About 5 pounds","About 200 pounds","None — they don't eat in winter"],
 "Northern winters demand large stores; ~60–90 lb is a common target.","Management"),
("Reversing brood boxes in early spring is done to…",
 ["Give the upward-moving cluster room to expand","Cool the hive","Trap mites","Harvest honey"],
 "The cluster drifts up over winter; reversing puts empty comb above them to fill.","Management"),
("You should generally avoid opening a hive when it is…",
 ["Cold, wet or windy","Sunny and calm","Mid-morning","During a nectar flow"],
 "Bad weather chills brood and makes bees defensive; pick mild, calm days.","Management"),
("A quick first step when you find a colony has swarmed is to…",
 ["Check that a viable queen cell or new queen remains","Add a honey super","Treat for mites","Feed pollen"],
 "After a swarm, confirm the colony can requeen itself from a remaining cell.","Management"),

# ---------------- Diseases (more depth) ----------------
("American foulbrood is so hard to eradicate because its spores…",
 ["Survive for decades and resist heat and chemicals","Die in a week","Only live on adult bees","Are killed by sunlight"],
 "AFB spores persist in equipment for 50+ years, which is why burning is often required.","Diseases"),
("European foulbrood often improves when the colony…",
 ["Hits a strong nectar flow or is requeened","Is closed up tight","Has supers removed","Is moved at night"],
 "Better nutrition and a brood break from requeening can let a colony recover from EFB.","Diseases"),
("Chalkbrood is most often triggered by…",
 ["Stress, chilling and poor ventilation","High Varroa loads","Pesticide spray","Robbing"],
 "The fungus takes hold in stressed, damp, or chilled brood; strong colonies resist it.","Diseases"),
("Nosema is best described as a disease of the adult bee's…",
 ["Digestive (gut) system","Wings","Brood","Stinger"],
 "Nosema fungi infect the gut lining, harming digestion and shortening life.","Diseases"),
("Sacbrood gets its name because affected larvae…",
 ["Form a fluid-filled sac","Turn to powder","Smell sour","Rope out 2 cm"],
 "The larva fills with fluid like a tiny water-filled bag, then darkens.","Diseases"),
("Deformed Wing Virus levels in a colony usually track with…",
 ["Varroa mite levels","Honey production","Queen age","Pollen color"],
 "DWV is vectored by Varroa, so crumpled wings signal a serious mite problem.","Diseases"),
("Which is NOT a honey bee brood disease?",
 ["Nosema","American foulbrood","European foulbrood","Chalkbrood"],
 "Nosema is an adult gut disease; AFB, EFB and chalkbrood affect brood.","Diseases"),
("A reliable way to tell AFB from EFB in the field is that AFB larvae…",
 ["Rope out farther (2 cm+) and leave a hard, stuck scale","Die before capping","Smell sweet","Are easy to scrape out"],
 "AFB ropes long and leaves a scale that won't lift; EFB usually kills larvae before capping.","Diseases"),
]
