# Latin / scientific-name practice questions (original, factual taxonomy).
# Same (q, opts, why, cat) format; opts[0] is correct (the app shuffles).
# cat = "Latin Names" — a pickable topic, also included in "All concept topics".
LATIN = [
# ---- Honey bee species & subspecies ----
("What is the scientific name of the Western honey bee?",
 ["Apis mellifera","Apis cerana","Apis dorsata","Bombus terrestris"],
 "Apis mellifera — Apis is the genus, mellifera the species ('honey-bearing').","Latin Names"),
("The species name 'mellifera' means…",
 ["Honey-bearing / honey-maker","Stinging insect","Yellow and black","Social bee"],
 "Melli = honey, fera = bearer. So Apis mellifera is the 'honey-bearing bee.'","Latin Names"),
("What is the scientific name of the Italian honey bee?",
 ["Apis mellifera ligustica","Apis mellifera carnica","Apis mellifera caucasica","Apis cerana"],
 "Italians are Apis mellifera ligustica — light-colored and prolific.","Latin Names"),
("What is the scientific name of the Carniolan honey bee?",
 ["Apis mellifera carnica","Apis mellifera ligustica","Apis mellifera mellifera","Apis florea"],
 "Carniolans are Apis mellifera carnica — gentle, with rapid spring buildup.","Latin Names"),
("What is the scientific name of the Caucasian honey bee?",
 ["Apis mellifera caucasica","Apis mellifera ligustica","Apis mellifera scutellata","Apis dorsata"],
 "Caucasians are Apis mellifera caucasica, known for long tongues and heavy propolis.","Latin Names"),
("Africanized bees descend partly from which African subspecies?",
 ["Apis mellifera scutellata","Apis mellifera ligustica","Apis mellifera carnica","Apis cerana"],
 "A. m. scutellata, crossed with European bees, gave rise to the Africanized 'killer' bee.","Latin Names"),
("The European dark (German/black) honey bee is…",
 ["Apis mellifera mellifera","Apis mellifera ligustica","Apis mellifera caucasica","Apis dorsata"],
 "Apis mellifera mellifera is the dark northern-European subspecies.","Latin Names"),
("What is the scientific name of the Asian (Eastern) honey bee?",
 ["Apis cerana","Apis mellifera","Apis dorsata","Apis florea"],
 "Apis cerana is the Asian honey bee — original host of Varroa.","Latin Names"),
("What is the scientific name of the giant honey bee?",
 ["Apis dorsata","Apis florea","Apis cerana","Apis mellifera"],
 "Apis dorsata, the giant honey bee, builds large open-air single combs.","Latin Names"),
("What is the scientific name of the dwarf honey bee?",
 ["Apis florea","Apis dorsata","Apis cerana","Apis mellifera"],
 "Apis florea is the dwarf honey bee.","Latin Names"),

# ---- Mites ----
("What is the scientific name of the Varroa mite?",
 ["Varroa destructor","Varroa jacobsoni","Acarapis woodi","Aethina tumida"],
 "Varroa destructor is the mite that devastates Western honey bee colonies.","Latin Names"),
("Which Varroa species originally parasitized only the Asian honey bee?",
 ["Varroa jacobsoni","Varroa destructor","Acarapis woodi","Tropilaelaps"],
 "Varroa jacobsoni stayed on Apis cerana; V. destructor jumped to Apis mellifera.","Latin Names"),
("What is the scientific name of the tracheal mite?",
 ["Acarapis woodi","Varroa destructor","Aethina tumida","Galleria mellonella"],
 "Acarapis woodi lives in the bee's tracheae (breathing tubes).","Latin Names"),
("The tropilaelaps mite belongs to the genus…",
 ["Tropilaelaps","Varroa","Acarapis","Aethina"],
 "Tropilaelaps is a serious brood-parasitic mite genus, not yet established in the US.","Latin Names"),

# ---- Beetles & moths ----
("What is the scientific name of the small hive beetle?",
 ["Aethina tumida","Galleria mellonella","Achroia grisella","Varroa destructor"],
 "Aethina tumida slimes comb and honey, worst in warm, humid conditions.","Latin Names"),
("What is the scientific name of the GREATER wax moth?",
 ["Galleria mellonella","Achroia grisella","Aethina tumida","Acarapis woodi"],
 "Galleria mellonella is the greater wax moth.","Latin Names"),
("What is the scientific name of the LESSER wax moth?",
 ["Achroia grisella","Galleria mellonella","Aethina tumida","Ascosphaera apis"],
 "Achroia grisella is the lesser wax moth.","Latin Names"),

# ---- Pathogens ----
("Which bacterium causes American foulbrood?",
 ["Paenibacillus larvae","Melissococcus plutonius","Ascosphaera apis","Clostridium botulinum"],
 "Paenibacillus larvae forms tough spores that make AFB so persistent.","Latin Names"),
("Which bacterium causes European foulbrood?",
 ["Melissococcus plutonius","Paenibacillus larvae","Ascosphaera apis","Nosema apis"],
 "Melissococcus plutonius causes EFB, usually killing larvae before capping.","Latin Names"),
("Which fungus causes chalkbrood?",
 ["Ascosphaera apis","Paenibacillus larvae","Melissococcus plutonius","Nosema ceranae"],
 "Ascosphaera apis turns larvae into hard chalky mummies.","Latin Names"),
("The historic Nosema species linked with dysentery is…",
 ["Nosema apis","Nosema ceranae","Ascosphaera apis","Varroa destructor"],
 "Nosema apis is the long-known gut parasite associated with dysentery.","Latin Names"),
("The more recently spread Nosema species (from Asia) is…",
 ["Nosema ceranae","Nosema apis","Paenibacillus larvae","Aethina tumida"],
 "Nosema ceranae is the newer gut parasite of honey bees in North America.","Latin Names"),
("Which bacterium produces the toxin behind infant botulism (a honey concern)?",
 ["Clostridium botulinum","Paenibacillus larvae","Melissococcus plutonius","Ascosphaera apis"],
 "Clostridium botulinum spores are why honey isn't fed to infants under 1.","Latin Names"),

# ---- Other insects ----
("Yellowjackets belong to the genera Vespula and…",
 ["Dolichovespula","Bombus","Apis","Galleria"],
 "Social yellow-and-black wasps in Vespula and Dolichovespula can rob hives in fall.","Latin Names"),
("Bumble bees belong to the genus…",
 ["Bombus","Apis","Vespula","Aethina"],
 "Bombus are the familiar fuzzy, social bumble bees in the family Apidae.","Latin Names"),

# ---- Classification of the honey bee ----
("To which FAMILY does the honey bee belong?",
 ["Apidae","Vespidae","Formicidae","Hymenoptera"],
 "Apidae is the largest bee family — honey bees, bumble bees, carpenter bees and more.","Latin Names"),
("To which ORDER does the honey bee belong?",
 ["Hymenoptera","Coleoptera","Diptera","Lepidoptera"],
 "Hymenoptera includes bees, wasps and ants — four membranous wings.","Latin Names"),
("To which GENUS does the honey bee belong?",
 ["Apis","Bombus","Vespula","Melissococcus"],
 "Apis is the honey-bee genus; the Western honey bee is Apis mellifera.","Latin Names"),
("To which CLASS does the honey bee belong?",
 ["Insecta","Arachnida","Mammalia","Apidae"],
 "Bees are in class Insecta (insects): three body segments, six legs.","Latin Names"),
("To which PHYLUM does the honey bee belong?",
 ["Arthropoda","Chordata","Mollusca","Hymenoptera"],
 "Arthropoda — jointed-legged invertebrates with an exoskeleton.","Latin Names"),
("Which is the correct order of classification, broad to specific?",
 ["Order → Family → Genus → Species","Species → Genus → Family → Order","Genus → Family → Order → Species","Family → Order → Genus → Species"],
 "Ranks narrow: Order, then Family, Genus, and finally Species.","Latin Names"),
("In a scientific name like Apis mellifera, the first word is the…",
 ["Genus","Species","Subspecies","Family"],
 "Genus is capitalized and comes first; the species name follows in lowercase.","Latin Names"),
("How should a scientific name like Apis mellifera be written?",
 ["Italicized, genus capitalized, species lowercase","All capital letters","All lowercase, no italics","Species first, then genus"],
 "Convention: italicized, with the genus capitalized and the species lowercase.","Latin Names"),
("The third word in a name like Apis mellifera ligustica indicates the…",
 ["Subspecies (race)","Genus","Family","Order"],
 "A third term denotes the subspecies/race — here, the Italian bee.","Latin Names"),
]
