# Oral-exam prep + seasonal calendar content.
# ORAL: summarized from the Cornell Oral Exam Rubric + Oral Topic List (Devon's course docs);
#       talking-point cards are original plain-English summaries of established bee facts.
# CALENDAR: summarized from the "Beekeeping Calendar for the Northeast" (Devon's course doc).

ORAL = {
 "intro": "The Cornell Master Beekeeper oral exam is a 15-minute presentation on a research topic of your choice, followed by a 5-minute question period. It's graded out of 272 points.",
 "grading": [
   "Content (107 pts): a strong intro (topic, background, why it matters to beekeeping), an accurate, master-level body, and a clear take-home conclusion.",
   "At least 5 outside sources must be presented and cited on your slides.",
   "Stay on topic, present in logical order, and define technical terms for an audience of experienced beekeepers (think a state/national conference).",
   "Presentation skills (55 pts): clear, well-paced delivery (12–15 min), good eye contact, and clean, uncluttered visuals.",
   "Experimental Design (55 pts): only if you ran an experiment — outcomes, treatment/control groups, methods, findings, and how they fit other research.",
 ],
 "template": [
   "Hook & define: open with something attention-getting, then say plainly what your topic is.",
   "Background: give the history/context so the audience is grounded.",
   "Why it matters: state clearly why a beekeeper should care.",
   "The science: walk through the key facts/mechanisms — cite 5+ sources on your slides, define terms.",
   "Take-home & Q&A: end with one clear message told as a story; prep answers for likely questions.",
 ],
 "cards": [
   {"topic":"How the waggle dance was deciphered", "points":[
     "What it is: a figure-8 'dance' on the comb that encodes direction (angle relative to the sun) and distance (length of the waggle run) to food or a nest site.",
     "History: decoded by Karl von Frisch, who won the 1973 Nobel Prize for it.",
     "Detail: very close sources produce a 'round dance' — really just a very short waggle.",
     "Why it matters: it's how a colony recruits foragers efficiently; touch on the dance-language vs. odor debate.",
     "Sources to find: von Frisch's work; Thomas Seeley's recruitment studies."]},
   {"topic":"Varroa feeding behavior", "points":[
     "Old understanding: mites feed on hemolymph (bee 'blood').",
     "Newer research (Ramsey et al., 2019): they primarily feed on the fat body.",
     "Why it matters: the fat body controls immunity, detox, and overwintering — explaining why mites make bees so virus-prone and winter-weak.",
     "Tie-in: reframes how we think about mite damage and treatment timing.",
     "Sources to find: Ramsey 2019 (PNAS); Honey Bee Health Coalition."]},
   {"topic":"Deformed Wing Virus", "points":[
     "An RNA virus that becomes serious when vectored and amplified by Varroa mites.",
     "Symptoms: crumpled, useless wings, bloated abdomens, drastically shortened lifespan.",
     "Covert vs. overt: low-level infections can be symptomless until mite loads rise.",
     "Why it matters: a leading driver of winter colony loss — controlling mites controls DWV.",
     "Sources to find: research on DWV variants and Varroa transmission."]},
   {"topic":"Parasitic Mite Syndrome", "points":[
     "A colony/brood decline driven by Varroa together with the viruses they carry — not one single pathogen.",
     "Signs: spotty brood, perforated/chewed cappings, crawling bees, dwindling population.",
     "Why it matters: easy to mistake for foulbrood; the real fix is mite management.",
     "Diagnosis: rule out AFB/EFB; correlate with mite counts."]},
   {"topic":"Africanized honey bees", "points":[
     "A hybrid of the African subspecies A. m. scutellata with European bees.",
     "History: escaped from a Brazilian breeding program in 1957 and spread through the Americas.",
     "Traits: highly defensive, quick to swarm/abscond — same species, but challenging to manage.",
     "ID: confirmed by morphometrics or DNA, not behavior alone.",
     "Why it matters: safety and public perception of beekeeping."]},
   {"topic":"Colony Collapse Disorder", "points":[
     "Defined around 2006–07: sudden loss of adult bees, very few dead bodies in or near the hive.",
     "Telltale: queen, brood, and food stores remain, and other bees don't immediately rob the dead-out.",
     "Causes: multifactorial — Varroa/viruses, pesticides, poor nutrition, and stress.",
     "Why it matters: it galvanized pollinator research and funding.",
     "Sources to find: USDA/EPA CCD reports."]},
   {"topic":"Drone congregation areas", "points":[
     "Specific spots in the air where drones gather, year after year, to await virgin queens.",
     "Mysteries: exactly how drones and queens find the same spots isn't fully understood.",
     "Function: mating away from home with many unrelated drones promotes genetic diversity.",
     "Tie-in: explains why open-mated queen genetics are hard to control."]},
   {"topic":"Honey bee mating", "points":[
     "A queen mates with ~12 (10–20) drones on 1–3 flights to a drone congregation area.",
     "She stores all that sperm in her spermatheca for life; the drone dies after mating.",
     "Polyandry (many mates) gives the colony genetic diversity and disease resilience.",
     "Mating flights and swarms are the only times a queen leaves the hive."]},
   {"topic":"Bee bread", "points":[
     "Pollen packed into cells with honey and glandular secretions, then fermented by microbes.",
     "It's the colony's main source of protein, fats, and vitamins — essential for brood.",
     "The fermentation/microbiome may improve preservation and nutrition.",
     "Why it matters: links nutrition, the gut microbiome, and colony health."]},
   {"topic":"The fat body", "points":[
     "An insect tissue that stores fat and glycogen and produces vitellogenin.",
     "Central to immunity, detoxification, longevity, and making winter bees.",
     "Varroa feeds on it — connecting mite damage to nearly every aspect of bee health.",
     "Why it matters: a unifying theme across nutrition, immunity, and overwintering."]},
   {"topic":"Crystallized honey", "points":[
     "Crystallization is glucose forming crystals — a natural process, not spoilage.",
     "It happens faster with a higher glucose-to-fructose ratio and at cool temperatures; floral source matters.",
     "Re-liquefy gently with low heat; creamed honey deliberately controls crystal size for a smooth spread.",
     "Why it matters: a common customer question and a marketing angle."]},
   {"topic":"Physiology of winter bees", "points":[
     "Winter bees live for months, not weeks — built for survival, not foraging.",
     "They have large fat bodies, high vitellogenin, and low juvenile hormone.",
     "They're reared in late summer/fall as pollen and brood pheromone decline.",
     "Why it matters: explains why August–September mite control is critical to winter survival."]},
   {"topic":"Tracheal mites", "points":[
     "Acarapis woodi — a tiny mite that lives and feeds inside the bee's tracheae (breathing tubes).",
     "Historically blamed for 'Isle of Wight disease' losses.",
     "Signs: crawling bees that can't fly, K-wing posture.",
     "Less of a problem today thanks to resistant stock; grease patties also help."]},
   {"topic":"Nosema (incl. N. ceranae)", "points":[
     "A microsporidian gut parasite (recently reclassified under Vairimorpha).",
     "N. ceranae spread more recently from Asia and shows less obvious dysentery than N. apis.",
     "Effects: dwindling adult populations, shortened life, poor nutrient absorption.",
     "Monitoring: spore counts; management focuses on reducing stress and replacing old comb."]},
 ],
 # Full Cornell oral topic list (titles) — browse and pick one to present on.
 "topics": [
  '"Murder Hornets" and honey bees','A closer look at chalkbrood','A history of beekeeping in New York',
  "A Master Beekeeper's critique of the Flow Hive",'Actual foraging patterns of bees during crop pollination',
  'Africanized honey bees','Alarm pheromone','Almond pollination in California','Amazing antennae',
  'An in-depth look at juvenile hormone','An up-close look at the corbiculae: Form and function',
  'Antibiotic resistance in beekeeping','Bait hives','Bee aging','Bee bread','Bee flight','Bee sting allergies',
  'Beekeeper health in the bee yard','Beekeeping in the Middle Ages','Beekeeping with stingless bees',
  'Bees can do math!','Bees in folklore','Bees in the Arnot Forest','Behaviors of the giant honey bee (Apis dorsata)',
  'Biology of pollination','Black queen cell virus','Brood breaks: Research and guide',
  'Building a successful treatment-free apiary','Can managed bees threaten the health of wild bees?',
  'Causes of queen issues','Chronic bee paralysis virus','Colony collapse disorder',
  'Comparing mite-monitoring strategies','Consumer preferences for buying honey',
  'Crystallized honey: Why it happens and what to do about it','Deformed wing virus',
  'Development during honey bee pupation','Drift behavior','Drone congregation areas: Facts and mysteries',
  'Early beekeeping in Europe','Early beekeeping in the Middle East','Early signs of swarming',
  'Entomophagy: Humans eating bee brood','Enzymes in honey','Evaluating breeder queens','Evolution of the stinger',
  'Fake food: Adulterated honey','Fat body','Floral fidelity','Fungi as medicine for bee viruses',
  'Glyphosate in honey','Grades of sociality','Hemolymph','History of AFB in New York State',
  'Honey bee biology during winter','Honey bee gut microbiome','Honey bee mating','Honey bee probiotics',
  'Honey bee vision','Honey composition and properties','Honey market in the U.S.','Honey packaging for sales',
  'Honeydew honey','How adjuvants in pesticides impact bees','How bees build comb',
  'How bees protect elephants and support African agriculture','How bees use sound/vibration to communicate',
  'How different bee stocks compare in northern climates','How do bees choose who will be the emergency queen?',
  'How do mites develop resistance to miticides?','How fungicides can impact honey bees',
  'How heat impacts honey quality','How hive insulation impacts winter colonies',
  'How honey bees optimize food collection and storage','How pollen supplementation impacts colony growth',
  'How small hive beetles interact with bees in the hive','How the waggle dance was deciphered',
  'How to make creamed honey','How to win a honey show','How Varroa affects deformed wing virus transmission',
  'Hydroxymethylfurfural in honey','Impact of aerial insecticide spraying','Impact of chlorpyrifos on bees',
  'Impact of clothianidin on bees','Impact of imidacloprid on bees','Impact of thiamethoxam on bees',
  'Importation of bees into North America','Insights from the honey bee genome',
  'Is palynology accurate for identifying nectar?','Isle of Wight Disease','Israeli acute paralysis virus',
  'Life of a larva','Management techniques that maximize honey production','Mead in culture and history',
  'Medicinal properties of honey','Memory capabilities of honey bees','Nectar preferences by honey bees',
  'Neonicotinoids in honey','Nestmate recognition','Non-waggle bee dances','Nosema ceranae',
  'Overwintering nucs in northern climates','Parasitic mite syndrome',
  'Pheromones & dance signals of a bivouac of swarming bees','Physiology of "winter" bees',
  'Piping, quacking, and tooting','Planting habitat to improve pollinator communities',
  'Poisonous and hallucinogenic honeys','Pollen digestion in bees','Prehistoric honey hunting',
  'Preventing wax moths in stored equipment','Production of comb honey','Pros and cons of plastic foundation',
  'Queen bee fighting behavior','Raising queens for a small operation','Role of insulation in winter',
  'Skep hive beekeeping','Soil health, plant diversity, and bee floral rewards',
  'Successful wintering practices in my region','The art of bee hunting','The biology of AFB','The biology of EFB',
  'The business of manuka honey','The dark side of dark comb','The diversity of bees in the U.S.',
  'The efficacy of colony spacing as Varroa control','The efficacy of drone comb frames as Varroa control',
  'The efficacy of screened bottom boards as Varroa control','The efficacy of swarming as Varroa control',
  'The efficacy of using oxalic acid when brood is present','The power of citizen science in bee research',
  'The roles of climate change in bumble bee declines','The royal jelly industry in China',
  'The Russian bee breeding program','The Saskatraz breeding program','The squash bee',
  'The top causes of winter loss','The unique Cape honey bee subspecies','Tracheal mites',
  'Tropilaelaps: The next invader?','Using sticky boards to assess colony conditions','Varroa feeding behavior',
  'Viruses and diseases of queen bees','Water foraging by honey bees','What fares better: packages or nucs?',
  'Wintering bees in indoor facilities','Honey bee competition with native bees in urban areas',
 ],
}

CALENDAR = [
 {"m":"January","season":"Deep winter","hive":"Cluster tight; cleansing flights on warm (~50°F+) days; queen may lay a few eggs.","tasks":[
   "Don't open the hive — do an external check; put your ear to the upper box and listen, or tap and listen for a response.",
   "Heft the back for weight; if light, add dry sugar, fondant, or a candy board on a warm day.",
   "Keep the cover secured; clear ice from the entrance (snow around the hive is fine — it insulates).",
   "A few dead bees or fecal spots on the snow = a good sign they're alive.",
   "Order packages, nucs, and queens NOW — producers sell out fast.",
   "Take inventory; clean, repair, assemble, and paint equipment; check stored comb for wax moths."]},
 {"m":"February","season":"Late winter","hive":"Still clustered (now near the top); queen starts laying a little; starvation risk rising.","tasks":[
   "Still no need to open — evaluate as in January.",
   "Feed dry sugar or a candy board if light; starvation risk is climbing.",
   "Some beekeepers add pollen patties now to stimulate brood rearing.",
   "Finish any equipment prep."]},
 {"m":"March","season":"Early spring","hive":"Lowest adult population of the year before spring buildup; queen near full lay if pollen is available. HIGH starvation risk.","tasks":[
   "Most starvation happens now — they should have 3–4 combs of honey; keep feeding until forage is available.",
   "Move honey frames next to the cluster, or move an empty bottom box up.",
   "Mites are starting to build — no need to treat yet, just be aware.",
   "Consider pollen substitute to stimulate laying (use clean pollen)."]},
 {"m":"April","season":"Spring","hive":"Bringing in pollen/nectar on warm days; drone rearing begins. Still starvation risk if cold.","tasks":[
   "Quick brood/stores checks on the warmest days — don't chill the brood.",
   "Begin MONTHLY Varroa monitoring: treat if 2+ mites/100 bees. Ideal time for treatments that need supers off.",
   "Check every brood frame for American foulbrood.",
   "Install packages/nucs and feed them; wait ~2 weeks before inspecting new colonies.",
   "Remove winter wraps, insulation, and mouse guards; check bear fencing.",
   "Requeen underperformers; if rearing queens, start checking for swarm cells."]},
 {"m":"May","season":"Spring buildup / swarm season","hive":"Brood rearing in high gear. Swarm season starts mid-May (queen cups along frame bottoms). Mites building.","tasks":[
   "Inspect every 2 weeks: brood pattern, queen/eggs, room, pests. Keep records.",
   "Swarm control: add room/supers, keep the brood nest from being honey-bound, watch for swarm cells, split strong colonies.",
   "Add supers as boxes fill and the first flow starts; add a queen excluder if you like.",
   "Monitor Varroa (treat at 2+/100); a brood break (caging the queen or splitting) helps.",
   "Replace your 2 oldest frames per box.",
   "Best month to rear queens and catch swarms; set out bait hives."]},
 {"m":"June","season":"Peak season","hive":"Peak population (June–July). Swarm season continues; mites still building.","tasks":[
   "Inspect at least monthly (brood, queen, room, pests).",
   "Continue swarm control; this is prime queen-rearing time.",
   "Monitor Varroa (treat at 2+/100); drone-comb trapping or a brood break helps.",
   "Keep supers on during the flow — foundation draws well now.",
   "Extract spring honey after pulling supers — extract promptly to avoid hive beetles."]},
 {"m":"July","season":"Summer","hive":"Swarm season winds down mid-July; population still high. Heat → bearding/ventilating. Possible dearth. Mites build.","tasks":[
   "Inspect at least monthly; watch for robbing during a dearth.",
   "Provide a water source if it's hot and dry.",
   "Monitor Varroa; this is about your last chance to split.",
   "Keep supering through the flow (basswood/linden, etc.).",
   "Harvest as supers fill; extract promptly."]},
 {"m":"August","season":"Late summer — winter prep begins","hive":"Winter-bee rearing starts; mites usually PEAK Aug–Sep; second small swarm season; goldenrod flow.","tasks":[
   "Inspect thoroughly — make sure colonies can take the fall flow and overwinter.",
   "⚠️ Critical Varroa window: threshold drops to 3/100 — treat now to protect the winter bees.",
   "Aim for ~70–90 lb of honey for winter; feed 2:1 syrup if light.",
   "Check every brood frame for American foulbrood.",
   "Combine weak colonies; requeen if needed; add an upper entrance for ventilation."]},
 {"m":"September","season":"Early fall","hive":"Last month to get colonies winter-ready; mites may still peak; first frost mid-month.","tasks":[
   "Don't disrupt the brood nest — it hurts winter-bee production.",
   "Finish Varroa treatment (especially once honey supers are off).",
   "Ensure winter stores (70–90+ lb); feed heavy 2:1 syrup if light. Last good month to feed pollen.",
   "Combine doomed colonies rather than waste resources trying to overwinter them.",
   "Extract any fall honey immediately to prevent hive beetles."]},
 {"m":"October","season":"Fall — winterize","hive":"Little/no egg laying; cluster forms around 50°F; drones evicted.","tasks":[
   "Do a final mite check, then remove and store all Varroa treatments before winterizing.",
   "Winterize: pull excess supers and the excluder, secure the cover, add a mouse guard (confirm no mouse first) and entrance reducer.",
   "Confirm adequate stores; feed 2:1 if needed. Stop feeding pollen.",
   "Manage moisture: upper entrance, tilt the hive forward to drain; insulate carefully (moisture, not cold, kills).",
   "Move hives to a sunny winter yard if you like."]},
 {"m":"November","season":"Early winter","hive":"Cluster set; little to no egg laying.","tasks":[
   "Finish winterizing: wrap/insulate if desired, keep an upper entrance for moisture exhaust, tilt forward to drain.",
   "Freeze or store any comb that could harbor wax moths.",
   "Mostly hands-off now — leave them be."]},
 {"m":"December","season":"Deep winter","hive":"Cluster set; little to no laying. Quiet month.","tasks":[
   "Leave the cluster alone — just confirm covers and entrances are secure after storms.",
   "Heft for stores on a mild day; emergency dry sugar if very light.",
   "Plan next year: read, order early, and attend club meetings or bee school."]},
]
