# Varroa treatment comparison cards.
# Restored from commit 89d6bfc. Those cards had been edited straight into index.html's
# baked DATA blob, so the next build_data.py + assemble.py rebuild silently deleted 10 of
# the 16. Anything the app shows has to live in a .py file here or it will not survive a
# rebuild. Edit this file, then run build_data.py and assemble.py.

VARROA = [{'name': 'Apiguard',
  'ai': 'Thymol',
  'cls': 'Essential oil',
  'region': 'US only — Thymovar is the Canada-registered thymol equivalent, not Apiguard',
  'method': 'Tray with gel sits on brood frames',
  'dose': 'Single deep: 1 tray (50g) on top of the brood frames. Double deep: 1 tray between the two boxes, plus a 25g reinforcement dose on top of the upper box',
  'eff': '74–95%',
  'cost': '$3.30–$6.80',
  'dur': '28 days (two 14-day applications)',
  'supers': 'No — supers off',
  'wait': 'Can super immediately after treatment ends',
  'temp': 'Needs warmth — roughly 60–105°F to vaporize properly'},
 {'name': 'Api Life Var',
  'ai': 'Thymol, eucalyptus oil, menthol',
  'cls': 'Essential oil',
  'region': 'US & Canada',
  'method': 'Tablets placed on the corners of the brood nest',
  'dose': 'Same dose either way, per the EPA label: 1 half-tablet (4 pieces) at the corners of the top box treats a colony of 8 to 20 frames — single deep through a full double deep. No extra tablets for the '
          'second box. Fresh half-tablet each of the 3 rounds',
  'eff': '70–90%',
  'cost': '$4.48–$7.12',
  'dur': '21–30 days (3 applications, 7–10 days apart)',
  'supers': 'No — supers off',
  'wait': '1 month after treatment ends',
  'temp': 'Needs warmth — roughly 60–105°F'},
 {'name': 'MiteAway Quick Strips (MAQS)',
  'ai': 'Formic acid',
  'cls': 'Organic acid',
  'region': 'US & Canada',
  'method': 'Pads placed on the brood nest',
  'dose': "2 pads per hive regardless of box count — always on the top bars of the LOWER brood chamber (same spot whether it's a single or double deep)",
  'eff': '61–98%',
  'cost': '$4.40–$7.25',
  'dur': '7 days (2-strip dose), or 21 days using 1 strip at day 0 plus a 2nd strip at day 14',
  'supers': 'Yes — can be left on during treatment',
  'wait': 'Supers can stay on',
  'temp': 'Moderate temps only — about 50–85°F (too hot can kill brood/queen)',
  'note': "Still EPA-registered, but the Honey Bee Health Coalition's 9th ed. guide (June 2026) dropped it from its product table entirely — Formic Pro has effectively superseded it. New buyers should default "
          'to Formic Pro.'},
 {'name': 'Formic Pro',
  'ai': 'Formic acid',
  'cls': 'Organic acid',
  'region': 'US & Canada',
  'method': 'Strips laid across the top bars of the brood nest',
  'dose': "2 strips per hive regardless of box count (half a strip for a nuc, per NOD's own guidance) — always on the top bars of the LOWER brood chamber (same spot whether it's a single or double deep)",
  'eff': '83–97%',
  'cost': '$6.70–$7.00',
  'dur': '14 days (2-strip dose), or 20 days using 1 strip per 10-day application, applied twice',
  'supers': 'Yes — can be left on during treatment (US/Canada label)',
  'wait': 'Supers can stay on',
  'temp': '50–85°F only — above 85°F risks brood or queen loss'},
 {'name': 'Oxalic Acid',
  'ai': 'Oxalic acid dihydrate',
  'cls': 'Organic acid',
  'region': 'US & Canada (Api-Bioxal Powder brand)',
  'method': 'Dribble on brood nest, or vaporize at entrance',
  'dose': 'Dribble: 5mL of syrup solution per occupied seam, max 50mL/hive regardless of box count. Vaporize: 4g per brood chamber (current Api-Bioxal label) — 8g total for a double deep, in two batches if '
          "your vaporizer can't hold that much at once",
  'eff': '82–99%',
  'cost': '$0.25–$0.37',
  'dur': '10 minutes',
  'supers': 'No — supers off',
  'wait': '2 weeks',
  'temp': 'Best when brood is low/absent (late fall, broodless). Works in cool weather.'},
 {'name': 'VarroxSan',
  'ai': 'Oxalic acid dihydrate (slow-release strip)',
  'cls': 'Organic acid',
  'region': 'US & Canada',
  'method': 'Strips hung between brood frames',
  'dose': '4 strips per 10-frame brood box (1 strip per 2.5 frames of bees) for a single deep. Double deep: 4 strips in the lower box (where most bees/brood/mites are), plus up to 2 more in the top box only '
          "if it's full of bees — 6 max, not a flat 8",
  'eff': '92–98% (mfr-recorded average 96%)',
  'cost': '$8.00–$10.00',
  'dur': '42–56 days, then remove strips',
  'supers': 'Yes — zero withdrawal, can be left on during treatment',
  'wait': 'Supers can stay on',
  'temp': 'No restriction to apply; contact-based, so works best above ~60°F when bees are actively moving'},
 {'name': 'HopGuard 3',
  'ai': 'Hops beta acids',
  'cls': 'Organic acid',
  'region': 'US & Canada',
  'method': 'Strips inserted in the brood nest',
  'dose': 'Scales with total frames of bees, not per box: 1-5 FoB→1 strip, 6-10→2, 11-15→3, 16-20→4. So ~2 for a single deep, ~4 for a full double deep — not a flat double. Use up to 4 times per year',
  'eff': '75–95% (HBHC 9th ed.)',
  'cost': '$3.33–$3.80',
  'dur': '~2 weeks per application; never leave in past 30 days',
  'supers': 'Yes — but only harvest honey/wax from supers, never the treated brood chamber',
  'wait': 'Supers can stay on',
  'temp': '55–100°F'},
 {'name': 'Apivar',
  'ai': 'Amitraz',
  'cls': 'Synthetic',
  'region': 'US & Canada',
  'method': 'Insert strips into the brood nest',
  'dose': '2 strips per brood box (1 per 5 frames of bees) — 2 for a single deep, 4 total for a double deep',
  'eff': '95%',
  'cost': '$5.00–$6.90',
  'dur': '42–56 days',
  'supers': 'No — supers off',
  'wait': '2 weeks',
  'temp': 'Wide range',
  'note': 'Apivar 2.0 is a newer variant of this same product: 6–10 weeks instead of 42–56 days, with the 10-week option recommended when brood is still present.'},
 {'name': 'Amiflex',
  'ai': 'Amitraz',
  'cls': 'Synthetic',
  'region': 'US & Canada',
  'method': 'Premixed gel dosed onto wooden strips with a dosing gun',
  'dose': '2 doses of 3mL per brood box on wooden strips, at least 1 empty frame of gel-free space between strips. Low infestation: apply once. High infestation: 2nd dose at day 14',
  'eff': '56% single treatment with brood present (81–83% for two treatments); 98–100% single treatment when broodless',
  'cost': 'Check current pricing',
  'dur': '7 days (low infestation) or 21 days (high infestation, 2 doses)',
  'supers': 'No — remove all gel before adding supers; do not apply more than 2 times in a row before a honey flow',
  'wait': 'Remove remaining product before supering',
  'temp': 'No restriction, but avoid treating in winter when bees are not foraging'},
 {'name': 'Thymovar (Canada only)',
  'ai': 'Thymol',
  'cls': 'Essential oil',
  'region': 'Canada only — NOT registered for US use. Apiguard is the US thymol equivalent',
  'method': 'Impregnated strip',
  'dose': '1 strip for a single brood chamber, 2 strips for a double — applied twice, 3–4 weeks apart',
  'eff': '74–95% (warmer is more effective)',
  'cost': 'Check current pricing',
  'dur': '6–8 weeks total (two 3–4 week applications)',
  'supers': 'No — supers off',
  'wait': 'Post-harvest or approaching dormancy',
  'temp': '60–85°F'},
 {'name': 'Api-Bioxal RTU',
  'ai': 'Oxalic acid (ready-mixed liquid)',
  'cls': 'Organic acid',
  'region': 'US only — not the same registration as the Canada-legal Api-Bioxal powder',
  'method': 'Pre-mixed liquid dribbled directly onto bees — no mixing required',
  'dose': "5mL per occupied seam per brood box — no per-hive maximum, unlike the powder version's 50mL cap. Can repeat up to 4 times, 7–10 days apart, when brood is present",
  'eff': '70–99%, depending on repetitions and whether brood is present',
  'cost': 'Check current pricing',
  'dur': '10 minutes per application; up to 4 repeat applications',
  'supers': 'Yes — can be used with supers on',
  'wait': 'None specified',
  'temp': 'No restriction — safe at any temperature, any colony size',
  'note': 'No sugar in the mix, so bees are not tempted to eat it, and the stored solution never develops the toxic HMF that homemade dribble syrup can.'},
 {'name': 'MBG2X5G',
  'ai': 'L-glutamic acid',
  'cls': 'Organic acid',
  'region': 'US only',
  'method': 'Impregnated strip clipped between top bars',
  'dose': '1 strip per 3–4 frames of brood; replace once under 25% remains (about every 42 days). Prophylactic use: 1 strip per brood box',
  'eff': 'Not yet published — newly registered in 2025, registrant still gathering data',
  'cost': 'Check current pricing',
  'dur': 'About 42 days per strip; can be used continuously year-round',
  'supers': 'Yes — no restriction noted',
  'wait': 'None specified',
  'temp': 'No restriction — developed for continuous, year-round use',
  'note': 'Brand new to the market as of 2025. No independently confirmed efficacy numbers yet — worth watching, not yet a proven primary treatment.'},
 {'name': 'Norroa',
  'ai': 'Vadescana (RNA interference)',
  'cls': 'Genetic (RNAi)',
  'region': 'US only — sold exclusively through Mann Lake, not yet available in Canada',
  'method': 'Liquid pouch placed in the brood box — bees feed on it and carry it into brood food, where mites pick it up',
  'dose': '2 pouches per brood box (remove once emptied), or 1 pouch followed by a 2nd once the first is emptied. Max 2x/year, max 4 pouches per brood chamber per year',
  'eff': 'Prevents mite reproduction rather than a fast kill — maintains or reduces mite levels for up to 18 weeks when applied with open brood present and mites under 3%. EPA field trials reported over 90% '
         'success in mite prevention',
  'cost': 'Sold exclusively through Mann Lake — check current pricing',
  'dur': 'Up to 18 weeks of protection per application',
  'supers': 'No — avoid with supers on, since it needs to stay in the brood chamber',
  'wait': 'None specified',
  'temp': 'No restriction',
  'note': 'EPA-registered September 2025 — the first RNAi/genetic varroa treatment on the market (IRAC Group 35, a brand-new mode of action). Only works on open brood with mite levels already low, so treat it '
          'as a maintenance/prevention tool, not a rescue treatment for a heavily infested colony.'},
 {'name': 'Formic Acid 65% (Canada only)',
  'ai': 'Formic acid 65%',
  'cls': 'Organic acid',
  'region': 'Canada only — NOT registered for US use',
  'method': 'Liquid formic acid soaked into absorbent pads (dri-loc or MiteGone pads)',
  'dose': 'Dri-loc pad: 30–40mL per 2-story hive, up to 6 applications, one every 10 days. MiteGone pad: 120–125g per pad, applied every 10 days, 2x per year',
  'eff': '60–93%',
  'cost': 'Check current pricing',
  'dur': '20–30 days depending on method',
  'supers': 'No — remove 2 weeks before adding supers',
  'wait': 'Post-honey harvest',
  'temp': '50–86°F',
  'note': "A liquid, more concentrated and more hazardous to handle than Formic Pro's gel strips — the liquid and fumes are dangerous to the applicator. Not the same product as Formic Pro, and not legal for "
          'US use.'},
 {'name': 'DIY Formic Acid Pads ("meat pads")',
  'ai': 'Formic acid, 65%, homemade',
  'cls': 'DIY — NOT registered',
  'region': 'Not EPA/PMRA-registered anywhere — an unapproved method, not a legal product, in any US state or Canadian province',
  'method': "Butcher's absorbent meat-tray pads (e.g. Dri-Loc 50) hand-soaked in 65% formic acid and laid on the top bars",
  'dose': '35mL of 65% formic acid per pad. One published protocol (Ontario): 6 applications, 4 days apart',
  'eff': 'No independently published figure — researcher Randy Oliver describes results as inconsistent',
  'cost': 'Cheap materials (pads + bulk formic acid), but per Oliver: a lot of labor and trips to the yards for repeat dosing',
  'dur': '6 applications, 4 days apart, per the published Ontario protocol',
  'supers': 'No — do not use with supers on',
  'wait': 'Not applicable — this is not a legal treatment path',
  'temp': 'Similar window to other formic products, roughly 50–85°F',
  'note': 'Randy Oliver documented this method himself and states plainly: it is currently illegal. Only registered products — Formic Pro or the Canada-only Formic Acid 65% above — are legal to use. Included '
          'here for informational/historical interest only, not as a recommendation. Concentrated formic acid causes severe chemical burns. Source: '
          'scientificbeekeeping.com/the-learning-curve-part-3-the-natural-miticides/'},
 {'name': 'DIY OA/Glycerin Sponges ("Swedish sponges")',
  'ai': 'Oxalic acid dihydrate + vegetable glycerin, homemade',
  'cls': 'DIY — NOT registered',
  'region': 'Not EPA/PMRA-registered — this is the experimental method VarroxSan was later developed from',
  'method': 'Equal weights of oxalic acid dihydrate and vegetable glycerin heated together (never above 160°F) until dissolved, then soaked into cellulose sponges or shop towels',
  'dose': "1:1 ratio by weight. Max 50g oxalic acid dihydrate total, in saturated carrier, per lower brood box — Oliver's shop-towel version worked out to about 18g OA per hive using two half towels",
  'eff': "No independently published figure — this was Oliver's own testing that helped inform VarroxSan's later commercial development",
  'cost': 'Cheap bulk materials (OA powder, glycerin, towels or sponges), but requires careful heating and handling',
  'dur': 'Bees gradually remove or consume the carrier over about 2 months',
  'supers': 'No — do not use with supers on',
  'wait': 'Not applicable — this is not a legal treatment path',
  'temp': 'No stated restriction — same contact-based mechanism as VarroxSan',
  'note': "Randy Oliver's own words on this method: I in no way encourage the unregistered application of any pesticide — please wait until this method is approved by the EPA and your State before using it in "
          'your own hives. VarroxSan is the now-registered, legal commercial product built on this same idea — use VarroxSan instead of replicating this at home. Source: '
          'scientificbeekeeping.com/extended-release-oxalic-acid-progress-report-2019/'}]

VARROA_NOTE = 'Apistan and CheckMite+ are NOT recommended — they stay in wax for years and mites have developed resistance. Rotate treatments, remove strips promptly, and follow IPM. Resistance to Apivar has also been seen. Always monitor mite levels after treating to confirm it worked. Efficacy figures: Honey Bee Health Coalition, Tools for Varroa Management, 9th ed. (June 2026).'
